"""Shared voice-related test constants for server tests."""

from __future__ import annotations

# Env vars that affect ``default_voice_config_from_env`` / ``merge_voice_config``.
VOICE_ENV_KEYS = (
    "TIMBAL_STT_PROVIDER",
    "TIMBAL_STT_MODEL",
    "TIMBAL_TTS_MODEL",
    "ELEVENLABS_VOICE_ID",
    "TIMBAL_VOICE_ID",
    "TIMBAL_VOICE_LANGUAGE",
    "TIMBAL_VOICE_RECORDING_DIR",
    "TIMBAL_VOICE_RECORDING_LAYOUT",
    "TIMBAL_VOICE_RECORDING_BITRATE_KBPS",
    "TIMBAL_VOICE_RECORDING_UPLOAD",
    "TIMBAL_VOICE_AMBIENT_SOURCE",
    "TIMBAL_VOICE_AMBIENT_VOLUME",
    "TIMBAL_VOICE_FILLER",
    "TIMBAL_VOICE_FILLER_SYSTEM_PROMPT",
    "TIMBAL_VOICE_FILLER_MODEL",
    "TIMBAL_VOICE_FILLER_DELAY_SECS",
    "TIMBAL_VOICE_FILLER_REPEAT_SECS",
)
