"""Shared voice-related test constants for server tests."""

from __future__ import annotations

# Env vars that affect voice server behavior: ``default_voice_config_from_env``
# / ``merge_voice_config``, the single-session lifetime, and RTC ICE.
VOICE_ENV_KEYS = (
    "TIMBAL_STT_PROVIDER",
    "TIMBAL_STT_MODEL",
    "TIMBAL_TTS_MODEL",
    "ELEVENLABS_VOICE_ID",
    "TIMBAL_VOICE_ID",
    "TIMBAL_VOICE_LANGUAGE",
    "TIMBAL_VOICE_RECORDING_DIR",
    "TIMBAL_VOICE_RECORDING_LAYOUT",
    "TIMBAL_VOICE_RECORDING_BITRATE_KBPS",
    "TIMBAL_VOICE_RECORDING_UPLOAD",
    "TIMBAL_VOICE_AMBIENT_SOURCE",
    "TIMBAL_VOICE_AMBIENT_VOLUME",
    "TIMBAL_VOICE_FILLER",
    "TIMBAL_VOICE_FILLER_SYSTEM_PROMPT",
    "TIMBAL_VOICE_FILLER_MODEL",
    "TIMBAL_VOICE_FILLER_DELAY_SECS",
    "TIMBAL_VOICE_FILLER_REPEAT_SECS",
    "TIMBAL_VOICE_SINGLE_SESSION",
    "TIMBAL_VOICE_IDLE_EXIT_SECS",
    "TIMBAL_VOICE_ABANDON_SECS",
    "TIMBAL_VOICE_TRANSPORT",
    "TIMBAL_LIVEKIT_URL",
    "TIMBAL_LIVEKIT_TOKEN",
    "TIMBAL_LIVEKIT_ROOM",
    "TIMBAL_LIVEKIT_CALLER_IDENTITY",
    "TIMBAL_VOICE_CLIENT_CONFIG",
    "TIMBAL_VOICE_RTC_FORCE_RELAY",
    "TIMBAL_TURN_URL",
    "TIMBAL_TURN_USERNAME",
    "TIMBAL_TURN_PASSWORD",
)
