use std::fs::File;
use std::path::Path;

use color_eyre::Result;
use symphonia::core::audio::SampleBuffer as SymphoniaSampleBuffer;
use symphonia::core::codecs::DecoderOptions;
use symphonia::core::formats::FormatOptions;
use symphonia::core::io::MediaSourceStream;
use symphonia::core::meta::MetadataOptions;
use symphonia::core::probe::Hint;

/// One frame of the vectorscope animation: a set of (left, right) points.
pub type Frame = Vec<(f64, f64)>;

const FRAME_SIZE: usize = 512;
const HOP_SIZE: usize = 4096;

/// The precomputed frames binary, embedded at compile time.
/// Generated by: cargo run --bin precompute-frames -- input.mp3 src/scope_frames.bin
const EMBEDDED_FRAMES: &[u8] = include_bytes!("scope_frames.bin");

/// Load precomputed frames from the embedded binary. Instant startup.
pub fn load_frames() -> Vec<Frame> {
    if EMBEDDED_FRAMES.len() < 8 {
        return vec![];
    }

    let num_frames = u32::from_le_bytes(EMBEDDED_FRAMES[0..4].try_into().unwrap()) as usize;
    let points_per_frame = u32::from_le_bytes(EMBEDDED_FRAMES[4..8].try_into().unwrap()) as usize;

    let mut frames = Vec::with_capacity(num_frames);
    let mut offset = 8;

    for _ in 0..num_frames {
        let mut points = Vec::with_capacity(points_per_frame);
        for _ in 0..points_per_frame {
            if offset + 8 > EMBEDDED_FRAMES.len() {
                break;
            }
            let l = f32::from_le_bytes(EMBEDDED_FRAMES[offset..offset + 4].try_into().unwrap());
            let r =
                f32::from_le_bytes(EMBEDDED_FRAMES[offset + 4..offset + 8].try_into().unwrap());
            points.push((l as f64, r as f64));
            offset += 8;
        }
        frames.push(points);
    }

    frames
}

/// Decode an entire MP3 file and precompute all vectorscope frames.
/// Used by the precompute-frames tool, not at runtime.
pub fn precompute_frames(path: &Path) -> Result<Vec<Frame>> {
    let all_stereo = decode_all_stereo(path)?;

    let mut frames = Vec::new();
    let total_pairs = all_stereo.len() / 2;
    let mut offset = 0;

    while offset + FRAME_SIZE <= total_pairs {
        let points: Vec<(f64, f64)> = (0..FRAME_SIZE)
            .map(|i| {
                let idx = (offset + i) * 2;
                let left = all_stereo[idx] as f64;
                let right = all_stereo[idx + 1] as f64;
                (left, right)
            })
            .collect();
        frames.push(points);
        offset += HOP_SIZE;
    }

    Ok(frames)
}

fn decode_all_stereo(path: &Path) -> Result<Vec<f32>> {
    let file = File::open(path)?;
    let mss = MediaSourceStream::new(Box::new(file), Default::default());

    let mut hint = Hint::new();
    hint.with_extension("mp3");

    let probed = symphonia::default::get_probe().format(
        &hint,
        mss,
        &FormatOptions::default(),
        &MetadataOptions::default(),
    )?;

    let mut format = probed.format;
    let track = format
        .default_track()
        .ok_or_else(|| color_eyre::eyre::eyre!("no audio track"))?;
    let track_id = track.id;

    let mut decoder =
        symphonia::default::get_codecs().make(&track.codec_params, &DecoderOptions::default())?;

    let mut all: Vec<f32> = Vec::new();

    loop {
        let packet = match format.next_packet() {
            Ok(p) => p,
            Err(_) => break,
        };

        if packet.track_id() != track_id {
            continue;
        }

        let decoded = match decoder.decode(&packet) {
            Ok(d) => d,
            Err(_) => continue,
        };

        let spec = *decoded.spec();
        let num_frames = decoded.frames();
        let channels = spec.channels.count();

        let mut sample_buf = SymphoniaSampleBuffer::<f32>::new(num_frames as u64, spec);
        sample_buf.copy_interleaved_ref(decoded);
        let samples = sample_buf.samples();

        if channels >= 2 {
            for i in 0..num_frames {
                all.push(samples[i * channels]);
                all.push(samples[i * channels + 1]);
            }
        } else {
            for &s in &samples[..num_frames] {
                all.push(s);
                all.push(s);
            }
        }
    }

    Ok(all)
}
