#!/usr/bin/env python3
"""Emit PostgreSQL INSERTs for public.\"Costs\" from python/timbal/models.yaml.

Usage keys match timbal collectors:
  - OpenAI chat completions + Responses API + OpenAI-compatible providers:
      input_text_tokens, output_text_tokens, input_cached_tokens,
      input_audio_tokens, output_audio_tokens
  - OpenAI / xAI Responses API (ResponseCollector): web_search_requests; xAI also emits
      {tool_name}_requests for ResponseCustomToolCall (e.g. web_fetch_requests, x_keyword_search_requests).
  - Anthropic messages streaming (usage.model_dump() leaves):
      input_tokens, output_tokens, cache_read_input_tokens,
      cache_creation_input_tokens, ephemeral_5m_input_tokens, ephemeral_1h_input_tokens;
      server_tool_use leaves: web_fetch_requests, web_search_requests (unit: requests).

Rates are USD per single token for token rows. Prefer published post-promotion
prices; use published promotional rates when no post-promotion rates are available.
Generate only explicit catalog token prices. Unknown cache/audio/tool rates are omitted,
never estimated. Dedicated endpoints need deployment-specific billing.
Only global streaming rates are generated: Batch and inference geography need separate billing.
Anthropic code execution is billed by duration and is not priced here.
This is an upsert artifact: omitted/retired rates already in a database are NOT deleted.
Review existing Costs rows separately when applying a catalog retirement.

Backend splits usage keys on `:` into (cost_name, cost_unit) and looks up
``WHERE $1 LIKE c.name || '%' AND c.unit = $2``.
So ``name`` = timbal model id (prefix), ``unit`` = usage key (after the ``:``).
Example: usage key ``openai/gpt-4o:input_text_tokens`` → name=``openai/gpt-4o``, unit=``input_text_tokens``.
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
MODELS_YAML = ROOT / "python" / "timbal" / "models.yaml"

def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def fmt_rate(x: float) -> str:
    return f"{x:.12f}".rstrip("0").rstrip(".")


def append_cost_row(
    lines: list[str],
    *,
    timbal_model_id: str,
    base_desc: str,
    usage_key: str,
    rate: float,
    extra_desc: str = "",
) -> None:
    desc = f"{base_desc} — {usage_key.replace('_', ' ')}"
    if extra_desc:
        desc += f". {extra_desc}"
    lines.append(
        "INSERT INTO public.\"Costs\" (name, description, unit, currency, rate) VALUES ("
        f"{sql_str(timbal_model_id)}, {sql_str(desc)}, {sql_str(usage_key)}, 'USD', {fmt_rate(rate)}) "
        "ON CONFLICT (name, unit) DO UPDATE SET "
        "description = EXCLUDED.description, "
        "currency = EXCLUDED.currency, "
        "rate = EXCLUDED.rate, "
        "updated_at = NOW();"
    )


def main(*, output_path: Path | None = None, provider_filter: str | None = None) -> None:
    data = yaml.safe_load(MODELS_YAML.read_text(encoding="utf-8"))
    models = [m for m in data.get("models", []) if provider_filter is None or m["provider"] == provider_filter]

    lines: list[str] = [
        "-- Auto-generated by scripts/generate_costs_sql.py from python/timbal/models.yaml",
        "-- Table: public.\"Costs\" (name, description, unit, currency, rate)",
        "-- rate = USD per one unit (per token for token rows; per request for *requests rows).",
        "-- name = timbal model id (e.g. openai/gpt-4o-mini), unit = usage_key after ':' (e.g. input_text_tokens).",
        "-- Backend splits usage key on ':' → (name, unit) and does WHERE $1 LIKE name || '%' AND unit = $2.",
        "-- Global streaming rates: post-promotion when published; promotional rates otherwise.",
        "-- Unknown cache/audio/tool prices and dedicated endpoints are omitted.",
        "-- Upserts only: existing rows for omitted or retired models are not removed.",
        "",
        "BEGIN;",
        "",
    ]

    for m in models:
        mid: str = m["id"]
        if "/" not in mid:
            continue
        _, model_suffix = mid.split("/", 1)
        display = m.get("display_name") or model_suffix
        if m.get("dedicated_only"):
            lines.append(f"-- Skipped dedicated endpoint: {mid}")
            continue
        inp = m.get("input_price")
        out = m.get("output_price")
        provider: str = m.get("provider") or ""

        base_desc = f"{display} ({mid})"
        row_kw = {"lines": lines, "timbal_model_id": mid, "base_desc": base_desc}

        if provider == "anthropic":
            if inp is None or out is None:
                lines.append(f"-- Skipped unknown Anthropic pricing: {mid}")
                continue
            metrics = {
                "input_tokens": "input_price",
                "output_tokens": "output_price",
                "cache_read_input_tokens": "cached_input_price",
                # Legacy aggregate fallback assumes 5m; mixed/1h TTL requires the breakdown.
                "cache_creation_input_tokens": "cache_write_price",
                "ephemeral_5m_input_tokens": "cache_write_price",
                "ephemeral_1h_input_tokens": "cache_write_1h_price",
            }
            contexts = [("", m)]
            if m.get("long_context"):
                contexts.append(("_long_context", m["long_context"]))
            tiers = {"": 1.0}
            if "fast" in m.get("service_tiers", {}):
                tiers["_fast"] = m["service_tiers"]["fast"]
            for context_suffix, prices in contexts:
                for tier_suffix, multiplier in tiers.items():
                    for unit, field in metrics.items():
                        rate = prices.get(field)
                        if rate is None:
                            continue
                        append_cost_row(
                            **row_kw,
                            usage_key=unit + context_suffix + tier_suffix,
                            rate=rate * multiplier / 1_000_000,
                            extra_desc=("Assumes 5m TTL when breakdown is unavailable"
                                        if unit == "cache_creation_input_tokens" else "Anthropic published rate"),
                        )
            for unit, rate in {"web_fetch_requests": 0.0, "web_search_requests": 0.01}.items():
                append_cost_row(**row_kw, usage_key=unit, rate=rate, extra_desc="Anthropic published per-call fee")
        else:
            # Each usage unit must have an explicit published rate. No 50% cache heuristic.
            metrics = {
                "input_price": "input_text_tokens",
                "output_price": "output_text_tokens",
                "cached_input_price": "input_cached_tokens",
                "cache_write_price": "input_cache_write_tokens",
            }
            contexts = [("", m)]
            if m.get("long_context"):
                contexts.append(("_long_context", m["long_context"]))
            tiers = {"": 1.0, **{"_" + k: v for k, v in m.get("service_tiers", {}).items()}}
            for context_suffix, prices in contexts:
                for field, unit in metrics.items():
                    rate = prices.get(field)
                    if rate is None:
                        continue
                    for tier_suffix, multiplier in tiers.items():
                        append_cost_row(
                            **row_kw,
                            usage_key=unit + context_suffix + tier_suffix,
                            rate=float(rate) * multiplier / 1_000_000,
                            extra_desc="Published catalog rate",
                        )
            # OpenAI's shared search metric cannot distinguish GA web search
            # ($10/1K calls) from non-reasoning preview search ($25/1K).
            # Omit it until the collector distinguishes those tool variants.

    lines.append("")
    lines.append("COMMIT;")
    out_path = output_path or Path(__file__).resolve().parent / "costs_inserts.sql"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(models)} models)")  # noqa: T201 — CLI result


if __name__ == "__main__":
    main()
