# pyright: reportUnsupportedDunderAll=false

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .asana import (
        AsanaAddTaskToSection,
        AsanaCreateProject,
        AsanaCreateSubtask,
        AsanaCreateTask,
        AsanaCreateTaskComment,
        AsanaCreateTaskFromTemplate,
        AsanaDeleteTask,
        AsanaFindTaskById,
        AsanaGetTasksFromTaskList,
        AsanaListTaskStories,
        AsanaListTeams,
        AsanaListUserProjects,
        AsanaListWorkspaces,
        AsanaSearchProjects,
        AsanaSearchSections,
        AsanaSearchTasks,
        AsanaUpdateTask,
    )
    from .bash import Bash
    from .cala import CalaSearch
    from .cloudflare import (
        CloudflareCrawlCancel,
        CloudflareCrawlGet,
        CloudflareCrawlStart,
    )
    from .dynamics_business_central import (
        DynamicsBCCreateCustomer,
        DynamicsBCGetItemPrices,
        DynamicsBCGetSalesOrder,
        DynamicsBCUpdateCustomer,
    )
    from .dynamics_sales import (
        DynamicsSalesCreateCustomEntity,
        DynamicsSalesCreateOpportunity,
        DynamicsSalesFindContact,
    )
    from .edit import Edit
    from .elasticsearch import (
        ElasticsearchBulkOperations,
        ElasticsearchCreateIndex,
        ElasticsearchDeleteDocument,
        ElasticsearchGetDocument,
        ElasticsearchIndexDocument,
        ElasticsearchIngestAttachment,
        ElasticsearchListDocuments,
        ElasticsearchListIndices,
        ElasticsearchSearchDocuments,
        ElasticsearchUpdateDocument,
        ElasticsearchUpdateIndexSettings,
    )
    from .elevenlabs import (
        ElevenLabsAddVoice,
        ElevenLabsCreateAgent,
        ElevenLabsDownloadHistoryItems,
        ElevenLabsGetAudioFromHistoryItem,
        ElevenLabsGetModels,
        ElevenLabsGetVoicesWithDescriptions,
        ElevenLabsListAgents,
        ElevenLabsListHistory,
        ElevenLabsListPhoneNumbers,
        ElevenLabsMakeOutboundCall,
        ElevenLabsTextToSpeech,
    )
    from .excel import (
        MicrosoftExcelAddDataToTable,
        MicrosoftExcelClearSheet,
        MicrosoftExcelCreateSheet,
        MicrosoftExcelCreateTable,
        MicrosoftExcelCreateWorkbook,
        MicrosoftExcelDeleteSheet,
        MicrosoftExcelFindRow,
        MicrosoftExcelGetCellsInRange,
        MicrosoftExcelGetRowByIndex,
        MicrosoftExcelGetSheetById,
        MicrosoftExcelListSheets,
        MicrosoftExcelListWorkbooks,
        MicrosoftExcelReadFromSheet,
        MicrosoftExcelRenameSheet,
        MicrosoftExcelUpdateCell,
        MicrosoftExcelUpdateRow,
        MicrosoftExcelWriteToSheet,
    )
    from .fal import (
        FalQueueCancel,
        FalQueueResult,
        FalQueueStatus,
        FalQueueSubmit,
    )
    from .firecrawl import FirecrawlCrawl, FirecrawlExtract, FirecrawlMap, FirecrawlScrape, FirecrawlSearch
    from .gemini_images import (
        GeminiImagesAnalyzeImage,
        GeminiImagesEditImage,
        GeminiImagesGenerateImage,
        GeminiImagesGenerateImageWithReference,
        GeminiImagesImageToBase64,
    )
    from .gmail import (
        GmailAddLabel,
        GmailCreateDraft,
        GmailListLabels,
        GmailRemoveLabel,
        GmailReply,
        GmailSearch,
        GmailSend,
    )
    from .google_calendar import (
        GoogleCalendarCheckFreeSlots,
        GoogleCalendarCreateEvent,
        GoogleCalendarDeleteEvent,
        GoogleCalendarListEvents,
        GoogleCalendarUpdateAttendeeStatus,
        GoogleCalendarUpdateEvent,
    )
    from .google_docs import GoogleDocsCreate
    from .google_drive import (
        GoogleDriveCreateFile,
        GoogleDriveCreateFolder,
        GoogleDriveCreateSharedDrive,
        GoogleDriveGetDownloadLink,
        GoogleDriveGetFile,
        GoogleDriveSearchFiles,
        GoogleDriveSearchFolders,
        GoogleDriveUploadFile,
    )
    from .google_maps import (
        GoogleMapsNearbySearch,
        GoogleMapsPlaceDetails,
        GoogleMapsTextSearch,
        GoogleMapsValidateAddress,
    )
    from .google_sheets import (
        GoogleSheetsAddSheet,
        GoogleSheetsAppendValues,
        GoogleSheetsBatchGet,
        GoogleSheetsBatchUpdate,
        GoogleSheetsClearValues,
        GoogleSheetsCopySheet,
        GoogleSheetsCreateSheet,
        GoogleSheetsGetSheetNames,
        GoogleSheetsGetSpreadsheetInfo,
        GoogleSheetsLookupRow,
        GoogleSheetsShareSpreadsheet,
    )
    from .hubspot import (
        HubSpotCreateAssociation,
        HubSpotCreateCompany,
        HubSpotCreateContact,
        HubSpotCreateDeal,
        HubSpotCreateEngagement,
        HubSpotCreateProduct,
        HubSpotCreateTicket,
        HubSpotDeleteAssociation,
        HubSpotDeleteEngagement,
        HubSpotDeleteProduct,
        HubSpotDeleteTicket,
        HubSpotGdprDeleteContact,
        HubSpotGetAssociations,
        HubSpotGetAssociationTypes,
        HubSpotGetCallDispositions,
        HubSpotGetCompany,
        HubSpotGetContact,
        HubSpotGetDeal,
        HubSpotGetDealPipelines,
        HubSpotGetEngagement,
        HubSpotGetEngagements,
        HubSpotGetProduct,
        HubSpotGetRecentEngagements,
        HubSpotGetTicket,
        HubSpotGetUsers,
        HubSpotListCompanies,
        HubSpotListContacts,
        HubSpotListDeals,
        HubSpotListEngagements,
        HubSpotListProducts,
        HubSpotListTickets,
        HubSpotMergeContacts,
        HubSpotMergeTickets,
        HubSpotSearchCompanies,
        HubSpotSearchContacts,
        HubSpotSendEmail,
        HubSpotUpdateCompany,
        HubSpotUpdateContact,
        HubSpotUpdateDeal,
        HubSpotUpdateProduct,
        HubSpotUpdateTicket,
        UpdateEngagement,
    )
    from .knowledge_base import KnowledgeBaseQuery
    from .lancedb import (
        LanceDBCreateFTSIndex,
        LanceDBCreateTable,
        LanceDBDeleteRecords,
        LanceDBDescribeTable,
        LanceDBDropFTSIndex,
        LanceDBDropTable,
        LanceDBFullTextSearch,
        LanceDBHybridSearch,
        LanceDBInsertRecords,
        LanceDBListTables,
        LanceDBVectorSearch,
    )
    from .linkedin import (
        LinkedInSearch,
        LinkedInSearchCompanies,
        LinkedInSearchJobs,
        LinkedInSearchPeople,
    )
    from .mongodb import (
        MongoCreateDocument,
        MongoDeleteDocument,
        MongoExecuteAggregation,
        MongoFindDocument,
        MongoFindDocumentById,
        MongoSearchDocuments,
        MongoUpdateDocument,
        MongoUpdateDocuments,
    )
    from .netsuite import (
        NetSuiteCreateAccount,
        NetSuiteCreateAccountingPeriod,
        NetSuiteCreateAssemblyBuild,
        NetSuiteCreateAssemblyItem,
        NetSuiteCreateBillingAccount,
        NetSuiteCreateBillingSchedule,
        NetSuiteCreateBinTransfer,
        NetSuiteCreateCalendarEvent,
        NetSuiteCreateIntercompanyJournalEntry,
        NetSuiteCustomSuiteQL,
        NetSuiteDeleteAccount,
        NetSuiteDeleteAccountingPeriod,
        NetSuiteDeleteAssemblyBuild,
        NetSuiteDeleteAssemblyItem,
        NetSuiteDeleteBillingAccount,
        NetSuiteDeleteBillingSchedule,
        NetSuiteDeleteBinTransfer,
        NetSuiteDeleteCalendarEvent,
        NetSuiteDeleteIntercompanyJournalEntry,
        NetSuiteGetAccount,
        NetSuiteGetAssemblyBuild,
        NetSuiteGetAssemblyItem,
        NetSuiteGetBillingAccount,
        NetSuiteGetBillingSchedule,
        NetSuiteGetBinTransfer,
        NetSuiteGetCalendarEvent,
        NetSuiteGetIntercompanyJournalEntry,
        NetSuiteListAccounts,
        NetSuiteListAssemblyBuilds,
        NetSuiteListAssemblyItems,
        NetSuiteListBillingAccounts,
        NetSuiteListBillingSchedules,
        NetSuiteListBinTransfers,
        NetSuiteListCalendarEvents,
        NetSuiteListIntercompanyJournalEntries,
        NetSuiteSuiteQL,
        NetSuiteTransformAssemblyItemToBuild,
        NetSuiteTransformAssemblyItemToWorkOrder,
        NetSuiteTransformAssemblyToUnbuild,
        NetSuiteUpdateAssemblyBuild,
        NetSuiteUpdateAssemblyItem,
        NetSuiteUpdateBillingAccount,
        NetSuiteUpdateBillingSchedule,
        NetSuiteUpdateBinTransfer,
        NetSuiteUpdateCalendarEvent,
        NetSuiteUpdateIntercompanyJournalEntry,
        NetSuiteUpsertBillingAccount,
        NetSuiteUpsertBillingSchedule,
        NetSuiteUpsertBinTransfer,
        NetSuiteUpsertCalendarEvent,
    )
    from .onedrive import (
        OneDriveDownloadFile,
        OneDriveFindFile,
        OneDriveGetFile,
        OneDriveListFiles,
        OneDriveSearchFiles,
        OneDriveUploadFile,
    )
    from .outlook import (
        OutlookArchive,
        OutlookCreateDraft,
        OutlookForward,
        OutlookGetAttachments,
        OutlookReadEmails,
        OutlookSend,
        OutlookTrash,
        OutlookUpdateEmail,
    )
    from .pinecone import (
        PineconeCreateIndex,
        PineconeDeleteVectors,
        PineconeFetchVectors,
        PineconeIndexStats,
        PineconeListIndexes,
        PineconeQuery,
        PineconeUpsertVectors,
    )
    from .powerbi import (
        PowerBIGetDataset,
        PowerBIGetReport,
        PowerBIListDatasets,
        PowerBIListReports,
        PowerBIListWorkspaces,
        PowerBIQueryDataset,
    )
    from .read import Read
    from .replicate import (
        ReplicateCancelPrediction,
        ReplicateCreatePrediction,
        ReplicateGetPrediction,
        ReplicateSearchModels,
    )
    from .salesforce import (
        SalesforceCreateCase,
        SalesforceCreateComment,
        SalesforceCreateContact,
        SalesforceCreateLead,
        SalesforceCreateOpportunity,
        SalesforceCreateRecord,
        SalesforceCreateTask,
        SalesforceDeleteCase,
        SalesforceDeleteComment,
        SalesforceDeleteContact,
        SalesforceDeleteLead,
        SalesforceDeleteOpportunity,
        SalesforceDeleteTask,
        SalesforceGetLead,
        SalesforceGetTask,
        SalesforceQuery,
        SalesforceSearchLeads,
        SalesforceSearchTasks,
        SalesforceUpdateCase,
        SalesforceUpdateComment,
        SalesforceUpdateContact,
        SalesforceUpdateLead,
        SalesforceUpdateOpportunity,
        SalesforceUpdateTask,
    )
    from .scraperapi import (
        ScraperAPIAmazonProduct,
        ScraperAPIAmazonSearch,
        ScraperAPIAsyncScrape,
        ScraperAPIGoogleSearch,
        ScraperAPIScrape,
    )
    from .shopify import (
        ShopifyAdjustInventory,
        ShopifyCreateProduct,
        ShopifyDeleteProduct,
        ShopifyGetInventoryLevel,
        ShopifyGetProduct,
        ShopifyGetProducts,
        ShopifyGetShopDetails,
        ShopifyGetVariantInventoryItem,
        ShopifyUpdateInventoryTracking,
    )
    from .slack import (
        SlackAddReaction,
        SlackAddUserToChannel,
        SlackArchiveChannel,
        SlackCreateCanvas,
        SlackDeleteFile,
        SlackDeleteMessage,
        SlackDownloadFile,
        SlackGetConversationInfo,
        SlackGetFileInfo,
        SlackGetMessageThread,
        SlackGetUserPresence,
        SlackListChannels,
        SlackListFiles,
        SlackListPinnedItems,
        SlackListUsersInChannel,
        SlackPinMessage,
        SlackReadMessages,
        SlackRemoveFromChannel,
        SlackRemoveReaction,
        SlackSearchUsers,
        SlackSendAndWaitForResponse,
        SlackSendEphemeralMessage,
        SlackSendMessage,
        SlackUnarchiveChannel,
        SlackUnpinMessage,
        SlackUpdateChannelPurpose,
        SlackUpdateChannelTopic,
    )
    from .stripe import (
        CancelOrReversePayout,
        CancelPaymentIntent,
        CancelSubscription,
        CapturePaymentIntent,
        ConfirmPaymentIntent,
        CreateBillingMeter,
        CreateCustomer,
        CreateInvoice,
        CreateInvoiceLineItem,
        CreatePayment,
        CreatePayout,
        CreatePrice,
        CreateProduct,
        CreateSubscription,
        CreateUsageRecord,
        DeleteCustomer,
        DeleteInvoiceLineItem,
        DeleteOrVoidInvoice,
        FinalizeInvoice,
        ListBalanceHistory,
        ListCharges,
        ListCustomers,
        ListInvoices,
        ListPaymentIntents,
        ListPayouts,
        ListProducts,
        ListRefunds,
        RetrieveBalance,
        RetrieveCheckoutSession,
        RetrieveCheckoutSessionLineItems,
        RetrieveCustomer,
        RetrieveInvoice,
        RetrieveInvoiceLineItem,
        RetrievePaymentIntent,
        RetrievePayout,
        RetrievePrice,
        RetrieveProduct,
        RetrieveRefund,
        SearchCustomer,
        SearchSubscriptions,
        SendInvoice,
        SendRefund,
        UpdateCustomer,
        UpdateInvoice,
        UpdateInvoiceLineItem,
        UpdatePaymentIntent,
        UpdatePayout,
        UpdateRefund,
        VoidInvoice,
        WriteOffInvoice,
    )
    from .tavily import TavilyCrawl, TavilyExtract, TavilyMap, TavilySearch
    from .web_search import WebSearch
    from .write import Write
    from .xai import XSearch
    from .zendesk import (
        ZendeskAddTags,
        ZendeskAutocompleteCustomObjectRecords,
        ZendeskAutocompleteOrganizations,
        ZendeskAutocompleteProblems,
        ZendeskAutocompleteUsers,
        ZendeskBulkCreateMemberships,
        ZendeskBulkDeleteAutomations,
        ZendeskBulkDeleteGroupMemberships,
        ZendeskBulkDeleteMacros,
        ZendeskBulkDeleteOrganizationMemberships,
        ZendeskBulkDeleteOrganizations,
        ZendeskBulkDeleteTickets,
        ZendeskBulkDeleteTicketTriggers,
        ZendeskBulkDeleteUsers,
        ZendeskBulkDeleteViews,
        ZendeskBulkDeleteWorkspaces,
        ZendeskBulkMarkTicketsAsSpam,
        ZendeskBulkSetAgentAttributeValuesJob,
        ZendeskBulkUpdateDefaultCustomTicketStatuses,
        ZendeskBulkUpdateTicketFormStatuses,
        ZendeskChangeCommentFromPublicToPrivate,
        ZendeskChangePassword,
        ZendeskCheckHostMappingValidity,
        ZendeskCheckHostMappingValidityForExistingBrand,
        ZendeskCloneTicketForm,
        ZendeskCountActivities,
        ZendeskCountAuditsForTicket,
        ZendeskCountCustomObjectRecords,
        ZendeskCountDeletedUsers,
        ZendeskCountGroups,
        ZendeskCountOrganizations,
        ZendeskCountOrganizationTickets,
        ZendeskCountSatisfactionRatings,
        ZendeskCountTags,
        ZendeskCountTicketComments,
        ZendeskCountTicketFields,
        ZendeskCountTickets,
        ZendeskCountTicketsInView,
        ZendeskCountUsers,
        ZendeskCountViews,
        ZendeskCreateApprovalRequest,
        ZendeskCreateApprovalWorkflowInstance,
        ZendeskCreateAutomation,
        ZendeskCreateBatchJobForTicketTriggerCategories,
        ZendeskCreateBookmark,
        ZendeskCreateBrand,
        ZendeskCreateCustomObject,
        ZendeskCreateCustomObjectRecord,
        ZendeskCreateCustomRole,
        ZendeskCreateCustomTicketStatus,
        ZendeskCreateDeletionSchedule,
        ZendeskCreateDynamicContentItem,
        ZendeskCreateDynamicContentVariant,
        ZendeskCreateGroup,
        ZendeskCreateGroupMembership,
        ZendeskCreateGroupSlaPolicy,
        ZendeskCreateIdentity,
        ZendeskCreateMacro,
        ZendeskCreateManyDynamicContentVariants,
        ZendeskCreateManyMemberships,
        ZendeskCreateManyOrganizations,
        ZendeskCreateManyTickets,
        ZendeskCreateOauthClient,
        ZendeskCreateOauthToken,
        ZendeskCreateOrganization,
        ZendeskCreateOrganizationField,
        ZendeskCreateOrganizationMembership,
        ZendeskCreateOrganizationSubscription,
        ZendeskCreateOrUpdateOrganization,
        ZendeskCreateOrUpdateTicketFieldOption,
        ZendeskCreateOrUpdateUserFieldOption,
        ZendeskCreateQueue,
        ZendeskCreateRequest,
        ZendeskCreateResourceCollection,
        ZendeskCreateRoutingAttribute,
        ZendeskCreateRoutingAttributeValue,
        ZendeskCreateSatisfactionRating,
        ZendeskCreateSharingAgreement,
        ZendeskCreateSlaPolicy,
        ZendeskCreateSupportAddress,
        ZendeskCreateTarget,
        ZendeskCreateTicket,
        ZendeskCreateTicketField,
        ZendeskCreateTicketForm,
        ZendeskCreateTicketFormStatuses,
        ZendeskCreateTicketFormStatusesForCustomStatus,
        ZendeskCreateTicketFromTweet,
        ZendeskCreateTicketOrVoicemailTicket,
        ZendeskCreateTicketTrigger,
        ZendeskCreateTicketTriggerCategory,
        ZendeskCreateTokenForGrantType,
        ZendeskCreateTrialAccount,
        ZendeskCreateUser,
        ZendeskCreateUserField,
        ZendeskCreateView,
        ZendeskCreateWorkspace,
        ZendeskCustomObjectsLimit,
        ZendeskDeleteAutomation,
        ZendeskDeleteBookmark,
        ZendeskDeleteBrand,
        ZendeskDeleteCurrentSession,
        ZendeskDeleteCustomObject,
        ZendeskDeleteCustomObjectRecord,
        ZendeskDeleteCustomObjectRecordByExternalId,
        ZendeskDeleteCustomRole,
        ZendeskDeleteDeletionSchedule,
        ZendeskDeleteDynamicContentItem,
        ZendeskDeleteDynamicContentVariant,
        ZendeskDeleteGroup,
        ZendeskDeleteGroupMembership,
        ZendeskDeleteGroupSlaPolicy,
        ZendeskDeleteIdentity,
        ZendeskDeleteMacro,
        ZendeskDeleteMultipleSuspendedTickets,
        ZendeskDeleteMultipleTicketsPermanently,
        ZendeskDeleteOauthClient,
        ZendeskDeleteOrganization,
        ZendeskDeleteOrganizationField,
        ZendeskDeleteOrganizationMembership,
        ZendeskDeleteOrganizationSubscription,
        ZendeskDeleteQueue,
        ZendeskDeleteResourceCollection,
        ZendeskDeleteRoutingAttribute,
        ZendeskDeleteRoutingAttributeValue,
        ZendeskDeleteSession,
        ZendeskDeleteSharingAgreement,
        ZendeskDeleteSlaPolicy,
        ZendeskDeleteSupportAddress,
        ZendeskDeleteSuspendedTicket,
        ZendeskDeleteTarget,
        ZendeskDeleteTicket,
        ZendeskDeleteTicketField,
        ZendeskDeleteTicketFieldOption,
        ZendeskDeleteTicketForm,
        ZendeskDeleteTicketPermanently,
        ZendeskDeleteTicketTrigger,
        ZendeskDeleteTicketTriggerCategory,
        ZendeskDeleteUpload,
        ZendeskDeleteUser,
        ZendeskDeleteUserField,
        ZendeskDeleteUserFieldOption,
        ZendeskDeleteView,
        ZendeskDeleteWorkspace,
        ZendeskDetectBestLanguageForUser,
        ZendeskExecuteView,
        ZendeskExportAuditLogs,
        ZendeskExportSearchResults,
        ZendeskExportSuspendedTickets,
        ZendeskGenerateOauthClientSecret,
        ZendeskGetApprovalsByApprovalWorkflowId,
        ZendeskGetDeletionSchedule,
        ZendeskGetSourcesByTarget,
        ZendeskIncrementalOrganizationExport,
        ZendeskIncrementalSampleExport,
        ZendeskIncrementalTicketEventExport,
        ZendeskIncrementalTicketExportCursor,
        ZendeskIncrementalTicketExportTimeBased,
        ZendeskIncrementalUserExportCursor,
        ZendeskIncrementalUserExportTimeBased,
        ZendeskListAccountAttributes,
        ZendeskListActiveAutomations,
        ZendeskListActiveMacros,
        ZendeskListActiveTicketTriggers,
        ZendeskListActiveViews,
        ZendeskListActivities,
        ZendeskListAgentAttributeValues,
        ZendeskListAllTicketAudits,
        ZendeskListAssignableAgentsFromGroup,
        ZendeskListAssignableGroups,
        ZendeskListAssignableGroupsAndAgentsBasedOnSkill,
        ZendeskListAssignableGroupsOnAssigneeField,
        ZendeskListAssignableMemberships,
        ZendeskListAttributeValuesForAttribute,
        ZendeskListAttributeValuesForManyAgents,
        ZendeskListAuditLogs,
        ZendeskListAuditsForTicket,
        ZendeskListAutomations,
        ZendeskListAvailablePublicLocales,
        ZendeskListBookmarks,
        ZendeskListBrandAgentMemberships,
        ZendeskListBrands,
        ZendeskListCollaborators,
        ZendeskListComments,
        ZendeskListCustomObjectRecords,
        ZendeskListCustomObjects,
        ZendeskListCustomRoles,
        ZendeskListCustomTicketStatuses,
        ZendeskListDeletedTickets,
        ZendeskListDeletedUsers,
        ZendeskListDeletionSchedules,
        ZendeskListDynamicContentItems,
        ZendeskListDynamicContentVariants,
        ZendeskListEmailCcs,
        ZendeskListEmailNotifications,
        ZendeskListFollowers,
        ZendeskListGlobalOauthClients,
        ZendeskListGroupMemberships,
        ZendeskListGroups,
        ZendeskListGroupSlaPolicies,
        ZendeskListIdentities,
        ZendeskListJobStatuses,
        ZendeskListLocales,
        ZendeskListLocalesForAgent,
        ZendeskListMacroActionDefinitions,
        ZendeskListMacroAttachments,
        ZendeskListMacroCategories,
        ZendeskListMacros,
        ZendeskListMonitoredXHandles,
        ZendeskListOauthClients,
        ZendeskListOauthTokens,
        ZendeskListOrganizationFields,
        ZendeskListOrganizationMemberships,
        ZendeskListOrganizationMerges,
        ZendeskListOrganizations,
        ZendeskListOrganizationSubscriptions,
        ZendeskListPasswordRequirements,
        ZendeskListProblems,
        ZendeskListQueueDefinitions,
        ZendeskListQueues,
        ZendeskListRelationshipFilterDefinitions,
        ZendeskListRequestComments,
        ZendeskListRequests,
        ZendeskListResourceCollections,
        ZendeskListResourceTags,
        ZendeskListRoutingAttributeDefinitions,
        ZendeskListSatisfactionRatings,
        ZendeskListSatisfactionReasons,
        ZendeskListSearchResults,
        ZendeskListSessions,
        ZendeskListSharingAgreements,
        ZendeskListSlaPolicies,
        ZendeskListSupportAddresses,
        ZendeskListSupportedActionsForMacros,
        ZendeskListSuspendedTickets,
        ZendeskListTags,
        ZendeskListTargetFailures,
        ZendeskListTargets,
        ZendeskListTicketAttributeValues,
        ZendeskListTicketFieldOptions,
        ZendeskListTicketFields,
        ZendeskListTicketForms,
        ZendeskListTicketFormStatuses,
        ZendeskListTicketIncidents,
        ZendeskListTicketMetricEvents,
        ZendeskListTicketMetrics,
        ZendeskListTickets,
        ZendeskListTicketsFromView,
        ZendeskListTicketsFulfilledByUser,
        ZendeskListTicketStatuses,
        ZendeskListTicketTriggerCategories,
        ZendeskListTicketTriggerDefinitions,
        ZendeskListTicketTriggerRevisions,
        ZendeskListTicketTriggers,
        ZendeskListUserFieldOptions,
        ZendeskListUserFields,
        ZendeskListUsers,
        ZendeskListViews,
        ZendeskListViewsById,
        ZendeskListViewsCompact,
        ZendeskListWorkspaces,
        ZendeskMakeCommentPrivate,
        ZendeskMakeIdentityPrimary,
        ZendeskMarkTicketAsSpam,
        ZendeskMergeOrganizationWithAnotherOrganization,
        ZendeskMergeTickets,
        ZendeskOpenTicketInAgentBrowser,
        ZendeskOpenUserProfileInAgentWorkspace,
        ZendeskPermanentlyDeleteUser,
        ZendeskPreviewTicketCount,
        ZendeskPreviewViews,
        ZendeskPushContentToSupport,
        ZendeskRecoverMultipleSuspendedTickets,
        ZendeskRecoverSuspendedTicket,
        ZendeskRedactChatComment,
        ZendeskRedactChatCommentAttachment,
        ZendeskRedactCommentAttachment,
        ZendeskRedactStringInComment,
        ZendeskRedactTicketCommentInAgentWorkspace,
        ZendeskRemoveTags,
        ZendeskRenewCurrentSession,
        ZendeskReorderGroupSlaPolicies,
        ZendeskReorderOrganizationField,
        ZendeskReorderQueues,
        ZendeskReorderSlaPolicies,
        ZendeskReorderTicketFields,
        ZendeskReorderTicketForms,
        ZendeskReorderUserField,
        ZendeskReorderWorkspaces,
        ZendeskReportChannelbackErrorToZendesk,
        ZendeskRequestUserVerification,
        ZendeskRestoreDeletedTicket,
        ZendeskRestoreMultipleDeletedTickets,
        ZendeskRetrieveSlaPolicyFilterDefinitions,
        ZendeskRevokeOauthToken,
        ZendeskSearchArticles,
        ZendeskSearchAutomations,
        ZendeskSearchCustomObjectRecords,
        ZendeskSearchMacros,
        ZendeskSearchOrganizations,
        ZendeskSearchRequests,
        ZendeskSearchTags,
        ZendeskSearchTickets,
        ZendeskSearchTicketTriggers,
        ZendeskSearchUsers,
        ZendeskSearchViews,
        ZendeskSetAgentAttributeValues,
        ZendeskSetCustomObjectRecordByExternalId,
        ZendeskSetGroupMembershipAsDefault,
        ZendeskSetOrganizationAsDefault,
        ZendeskSetOrganizationMembershipAsDefault,
        ZendeskSetTags,
        ZendeskSetTicketAttributeValues,
        ZendeskSetUserPassword,
        ZendeskShowActivity,
        ZendeskShowApprovalRequest,
        ZendeskShowAttachment,
        ZendeskShowAudit,
        ZendeskShowAuditLog,
        ZendeskShowAutomation,
        ZendeskShowBrand,
        ZendeskShowBrandAgentMembership,
        ZendeskShowChangesToTicket,
        ZendeskShowCurrentLocale,
        ZendeskShowCurrentSession,
        ZendeskShowCustomObject,
        ZendeskShowCustomObjectRecord,
        ZendeskShowCustomRole,
        ZendeskShowCustomTicketStatus,
        ZendeskShowDeletedUser,
        ZendeskShowDynamicContentItem,
        ZendeskShowDynamicContentVariant,
        ZendeskShowEmailNotification,
        ZendeskShowGroup,
        ZendeskShowGroupMembership,
        ZendeskShowGroupSlaPolicy,
        ZendeskShowIdentity,
        ZendeskShowJobStatus,
        ZendeskShowLocale,
        ZendeskShowMacro,
        ZendeskShowMacroAttachment,
        ZendeskShowMacroReplica,
        ZendeskShowManyDynamicContentItems,
        ZendeskShowManyEmailNotifications,
        ZendeskShowManyJobStatuses,
        ZendeskShowManyOrganizations,
        ZendeskShowManyTicketForms,
        ZendeskShowManyTickets,
        ZendeskShowManyUsers,
        ZendeskShowMonitoredXHandle,
        ZendeskShowOauthClient,
        ZendeskShowOauthToken,
        ZendeskShowOrganization,
        ZendeskShowOrganizationField,
        ZendeskShowOrganizationMembership,
        ZendeskShowOrganizationMerge,
        ZendeskShowOrganizationRelatedInformation,
        ZendeskShowOrganizationSubscription,
        ZendeskShowQueue,
        ZendeskShowRequest,
        ZendeskShowRequestComment,
        ZendeskShowResourceCollection,
        ZendeskShowRoutingAttribute,
        ZendeskShowRoutingAttributeValue,
        ZendeskShowSatisfactionRating,
        ZendeskShowSatisfactionReason,
        ZendeskShowSearchResultsCount,
        ZendeskShowSelf,
        ZendeskShowSession,
        ZendeskShowSettings,
        ZendeskShowSharingAgreement,
        ZendeskShowSlaPolicy,
        ZendeskShowSupportAddress,
        ZendeskShowSuspendedTicket,
        ZendeskShowTarget,
        ZendeskShowTargetFailure,
        ZendeskShowTicket,
        ZendeskShowTicketAfterChanges,
        ZendeskShowTicketField,
        ZendeskShowTicketFieldOption,
        ZendeskShowTicketForm,
        ZendeskShowTicketMetrics,
        ZendeskShowTicketTrigger,
        ZendeskShowTicketTriggerCategory,
        ZendeskShowUser,
        ZendeskShowUserField,
        ZendeskShowUserFieldOption,
        ZendeskShowUserRelatedInformation,
        ZendeskShowView,
        ZendeskShowWorkspace,
        ZendeskSuspendedTicketAttachments,
        ZendeskTicketBulkImport,
        ZendeskTicketImport,
        ZendeskTicketRelatedInformation,
        ZendeskUnassignOrganization,
        ZendeskUpdateAccountSettings,
        ZendeskUpdateApprovalRequestStatus,
        ZendeskUpdateAttachmentForMalware,
        ZendeskUpdateAutomation,
        ZendeskUpdateBrand,
        ZendeskUpdateCustomObject,
        ZendeskUpdateCustomObjectRecord,
        ZendeskUpdateCustomRole,
        ZendeskUpdateCustomTicketStatus,
        ZendeskUpdateDeletionSchedule,
        ZendeskUpdateDynamicContentItem,
        ZendeskUpdateDynamicContentVariant,
        ZendeskUpdateGroup,
        ZendeskUpdateGroupSlaPolicy,
        ZendeskUpdateIdentity,
        ZendeskUpdateMacro,
        ZendeskUpdateManyAutomations,
        ZendeskUpdateManyDynamicContentVariants,
        ZendeskUpdateManyMacros,
        ZendeskUpdateManyOrganizations,
        ZendeskUpdateManyTickets,
        ZendeskUpdateManyViews,
        ZendeskUpdateOauthClient,
        ZendeskUpdateOrganization,
        ZendeskUpdateOrganizationField,
        ZendeskUpdateQueue,
        ZendeskUpdateRequest,
        ZendeskUpdateResourceCollection,
        ZendeskUpdateRoutingAttribute,
        ZendeskUpdateRoutingAttributeValue,
        ZendeskUpdateSharingAgreement,
        ZendeskUpdateSlaPolicy,
        ZendeskUpdateSupportAddress,
        ZendeskUpdateTarget,
        ZendeskUpdateTicket,
        ZendeskUpdateTicketField,
        ZendeskUpdateTicketForm,
        ZendeskUpdateTicketTrigger,
        ZendeskUpdateTicketTriggerCategory,
        ZendeskUpdateUser,
        ZendeskUpdateUserField,
        ZendeskUpdateView,
        ZendeskUpdateWorkspace,
        ZendeskUploadFiles,
        ZendeskValidateToken,
        ZendeskVerifyIdentity,
        ZendeskVerifySubdomainAvailability,
        ZendeskVerifySupportAddressForwarding,
    )
    from .zoho_crm import (
        ZohoCrmConvertLead,
        ZohoCrmCreateObject,
        ZohoCrmDownloadAttachment,
        ZohoCrmGetObject,
        ZohoCrmListFields,
        ZohoCrmListModules,
        ZohoCrmListObjects,
        ZohoCrmSearchObjects,
        ZohoCrmUpdateObject,
        ZohoCrmUploadAttachment,
    )
__all__ = [
    "Bash",
    "CalaSearch",
    "Edit",
    "FirecrawlCrawl",
    "FirecrawlExtract",
    "FirecrawlMap",
    "FirecrawlScrape",
    "FirecrawlSearch",
    "GmailAddLabel",
    "GmailCreateDraft",
    "GmailListLabels",
    "GmailRemoveLabel",
    "GmailReply",
    "GmailSearch",
    "GmailSend",
    "GoogleCalendarCheckFreeSlots",
    "GoogleCalendarCreateEvent",
    "GoogleCalendarDeleteEvent",
    "GoogleCalendarListEvents",
    "GoogleCalendarUpdateAttendeeStatus",
    "GoogleCalendarUpdateEvent",
    "GoogleDocsCreate",
    "GoogleDriveCreateFile",
    "GoogleDriveCreateFolder",
    "GoogleDriveCreateSharedDrive",
    "GoogleDriveGetDownloadLink",
    "GoogleDriveGetFile",
    "GoogleDriveSearchFiles",
    "GoogleDriveSearchFolders",
    "GoogleDriveUploadFile",
    "GoogleSheetsAddSheet",
    "GoogleSheetsAppendValues",
    "GoogleSheetsBatchGet",
    "GoogleSheetsBatchUpdate",
    "GoogleSheetsClearValues",
    "GoogleSheetsCopySheet",
    "GoogleSheetsCreateSheet",
    "GoogleSheetsGetSheetNames",
    "GoogleSheetsGetSpreadsheetInfo",
    "GoogleSheetsLookupRow",
    "GoogleSheetsShareSpreadsheet",
    "GoogleMapsNearbySearch",
    "GoogleMapsPlaceDetails",
    "GoogleMapsTextSearch",
    "GoogleMapsValidateAddress",
    "KnowledgeBaseQuery",
    "OutlookArchive",
    "OutlookCreateDraft",
    "OutlookForward",
    "OutlookGetAttachments",
    "OutlookReadEmails",
    "OutlookSend",
    "OutlookTrash",
    "OutlookUpdateEmail",
    "PineconeCreateIndex",
    "PineconeDeleteVectors",
    "PineconeFetchVectors",
    "PineconeIndexStats",
    "PineconeListIndexes",
    "PineconeQuery",
    "PineconeUpsertVectors",
    "Read",
    "ScraperAPIAmazonProduct",
    "ScraperAPIAmazonSearch",
    "ScraperAPIAsyncScrape",
    "ScraperAPIGoogleSearch",
    "ScraperAPIScrape",
    "TavilyCrawl",
    "TavilyExtract",
    "TavilyMap",
    "TavilySearch",
    "WebSearch",
    "Write",
    "XSearch",
    "ListCharges",
    "CreateCustomer",
    "SearchCustomer",
    "CreatePayment",
    "SendRefund",
    "UpdateCustomer",
    "RetrieveCustomer",
    "ListCustomers",
    "DeleteCustomer",
    "UpdatePaymentIntent",
    "RetrievePaymentIntent",
    "ListPaymentIntents",
    "ConfirmPaymentIntent",
    "CapturePaymentIntent",
    "CancelPaymentIntent",
    "UpdateRefund",
    "RetrieveRefund",
    "ListRefunds",
    "CreateInvoice",
    "UpdateInvoice",
    "RetrieveInvoice",
    "ListInvoices",
    "SendInvoice",
    "FinalizeInvoice",
    "VoidInvoice",
    "WriteOffInvoice",
    "DeleteOrVoidInvoice",
    "CreateInvoiceLineItem",
    "UpdateInvoiceLineItem",
    "RetrieveInvoiceLineItem",
    "DeleteInvoiceLineItem",
    "CreateSubscription",
    "SearchSubscriptions",
    "CancelSubscription",
    "CreateProduct",
    "RetrieveProduct",
    "ListProducts",
    "CreatePrice",
    "RetrievePrice",
    "CreatePayout",
    "UpdatePayout",
    "RetrievePayout",
    "ListPayouts",
    "CancelOrReversePayout",
    "RetrieveBalance",
    "ListBalanceHistory",
    "RetrieveCheckoutSession",
    "RetrieveCheckoutSessionLineItems",
    "CreateBillingMeter",
    "CreateUsageRecord",
    "SlackReadMessages",
    "SlackSendMessage",
    "SlackSendEphemeralMessage",
    "SlackCreateCanvas",
    "SlackDeleteMessage",
    "SlackGetMessageThread",
    "SlackPinMessage",
    "SlackUnpinMessage",
    "SlackListPinnedItems",
    "SlackGetUserPresence",
    "SlackSearchUsers",
    "SlackAddUserToChannel",
    "SlackRemoveFromChannel",
    "SlackListUsersInChannel",
    "SlackUpdateChannelTopic",
    "SlackUpdateChannelPurpose",
    "SlackArchiveChannel",
    "SlackUnarchiveChannel",
    "SlackGetConversationInfo",
    "SlackListChannels",
    "SlackAddReaction",
    "SlackRemoveReaction",
    "SlackListFiles",
    "SlackGetFileInfo",
    "SlackDownloadFile",
    "SlackDeleteFile",
    "SlackSendAndWaitForResponse",
    "LanceDBListTables",
    "LanceDBCreateTable",
    "LanceDBDropTable",
    "LanceDBInsertRecords",
    "LanceDBVectorSearch",
    "LanceDBFullTextSearch",
    "LanceDBHybridSearch",
    "LanceDBCreateFTSIndex",
    "LanceDBDropFTSIndex",
    "LanceDBDeleteRecords",
    "LanceDBDescribeTable",
    "HubSpotListContacts",
    "HubSpotGetContact",
    "HubSpotCreateContact",
    "HubSpotUpdateContact",
    "HubSpotSearchContacts",
    "HubSpotMergeContacts",
    "HubSpotGdprDeleteContact",
    "HubSpotListCompanies",
    "HubSpotGetCompany",
    "HubSpotCreateCompany",
    "HubSpotUpdateCompany",
    "HubSpotSearchCompanies",
    "HubSpotListDeals",
    "HubSpotGetDeal",
    "HubSpotCreateDeal",
    "HubSpotUpdateDeal",
    "HubSpotGetDealPipelines",
    "HubSpotListTickets",
    "HubSpotGetTicket",
    "HubSpotCreateTicket",
    "HubSpotUpdateTicket",
    "HubSpotDeleteTicket",
    "HubSpotMergeTickets",
    "HubSpotListProducts",
    "HubSpotGetProduct",
    "HubSpotCreateProduct",
    "HubSpotUpdateProduct",
    "HubSpotDeleteProduct",
    "HubSpotGetEngagements",
    "HubSpotGetEngagement",
    "HubSpotListEngagements",
    "HubSpotGetRecentEngagements",
    "HubSpotGetCallDispositions",
    "HubSpotCreateEngagement",
    "UpdateEngagement",
    "HubSpotDeleteEngagement",
    "HubSpotSendEmail",
    "HubSpotGetAssociations",
    "HubSpotCreateAssociation",
    "HubSpotDeleteAssociation",
    "HubSpotGetAssociationTypes",
    "HubSpotGetUsers",
    "ElevenLabsTextToSpeech",
    "ElevenLabsListPhoneNumbers",
    "ElevenLabsMakeOutboundCall",
    "ElevenLabsListAgents",
    "ElevenLabsGetModels",
    "ElevenLabsGetVoicesWithDescriptions",
    "ElevenLabsListHistory",
    "ElevenLabsGetAudioFromHistoryItem",
    "ElevenLabsDownloadHistoryItems",
    "ElevenLabsCreateAgent",
    "ElevenLabsAddVoice",
    "CloudflareCrawlStart",
    "CloudflareCrawlGet",
    "CloudflareCrawlCancel",
    "AsanaCreateProject",
    "AsanaListWorkspaces",
    "AsanaUpdateTask",
    "AsanaListUserProjects",
    "AsanaListTeams",
    "AsanaSearchTasks",
    "AsanaSearchSections",
    "AsanaSearchProjects",
    "AsanaListTaskStories",
    "AsanaGetTasksFromTaskList",
    "AsanaFindTaskById",
    "AsanaDeleteTask",
    "AsanaCreateTask",
    "AsanaCreateTaskFromTemplate",
    "AsanaCreateTaskComment",
    "AsanaCreateSubtask",
    "AsanaAddTaskToSection",
    "ZendeskCreateTicket",
    "ZendeskListTickets",
    "ZendeskShowTicket",
    "ZendeskUpdateTicket",
    "ZendeskSearchTickets",
    "ZendeskShowManyTickets",
    "ZendeskUpdateManyTickets",
    "ZendeskCountTickets",
    "ZendeskCreateManyTickets",
    "ZendeskDeleteTicket",
    "ZendeskBulkDeleteTickets",
    "ZendeskMarkTicketAsSpam",
    "ZendeskBulkMarkTicketsAsSpam",
    "ZendeskMergeTickets",
    "ZendeskTicketRelatedInformation",
    "ZendeskListCollaborators",
    "ZendeskListEmailCcs",
    "ZendeskListFollowers",
    "ZendeskListDeletedTickets",
    "ZendeskRestoreDeletedTicket",
    "ZendeskRestoreMultipleDeletedTickets",
    "ZendeskDeleteTicketPermanently",
    "ZendeskDeleteMultipleTicketsPermanently",
    "ZendeskListTicketIncidents",
    "ZendeskListProblems",
    "ZendeskAutocompleteProblems",
    "ZendeskCountOrganizationTickets",
    "ZendeskListUsers",
    "ZendeskShowUser",
    "ZendeskListGroups",
    "ZendeskShowGroup",
    "ZendeskCountGroups",
    "ZendeskCreateGroup",
    "ZendeskUpdateGroup",
    "ZendeskDeleteGroup",
    "ZendeskListAssignableGroups",
    "ZendeskListComments",
    "ZendeskCountTicketComments",
    "ZendeskMakeCommentPrivate",
    "ZendeskRedactTicketCommentInAgentWorkspace",
    "ZendeskRedactChatComment",
    "ZendeskRedactChatCommentAttachment",
    "ZendeskRedactStringInComment",
    "ZendeskListBookmarks",
    "ZendeskCreateBookmark",
    "ZendeskDeleteBookmark",
    "ZendeskListWorkspaces",
    "ZendeskShowWorkspace",
    "ZendeskCreateWorkspace",
    "ZendeskUpdateWorkspace",
    "ZendeskDeleteWorkspace",
    "ZendeskBulkDeleteWorkspaces",
    "ZendeskReorderWorkspaces",
    "ZendeskListViews",
    "ZendeskListViewsCompact",
    "ZendeskListViewsById",
    "ZendeskListActiveViews",
    "ZendeskCountViews",
    "ZendeskSearchViews",
    "ZendeskShowView",
    "ZendeskCreateView",
    "ZendeskUpdateView",
    "ZendeskUpdateManyViews",
    "ZendeskDeleteView",
    "ZendeskBulkDeleteViews",
    "ZendeskExecuteView",
    "ZendeskListTicketsFromView",
    "ZendeskCountTicketsInView",
    "ZendeskPreviewViews",
    "ZendeskPreviewTicketCount",
    "ZendeskCreateUser",
    "ZendeskUpdateUser",
    "ZendeskDeleteUser",
    "ZendeskSearchUsers",
    "ZendeskCountUsers",
    "ZendeskShowManyUsers",
    "ZendeskShowSelf",
    "ZendeskShowUserRelatedInformation",
    "ZendeskListDeletedUsers",
    "ZendeskShowDeletedUser",
    "ZendeskCountDeletedUsers",
    "ZendeskAutocompleteUsers",
    "ZendeskBulkDeleteUsers",
    "ZendeskPermanentlyDeleteUser",
    "ZendeskListTicketTriggerCategories",
    "ZendeskCreateTicketTriggerCategory",
    "ZendeskCreateBatchJobForTicketTriggerCategories",
    "ZendeskShowTicketTriggerCategory",
    "ZendeskUpdateTicketTriggerCategory",
    "ZendeskDeleteTicketTriggerCategory",
    "ZendeskListTicketTriggers",
    "ZendeskListActiveTicketTriggers",
    "ZendeskSearchTicketTriggers",
    "ZendeskShowTicketTrigger",
    "ZendeskListTicketTriggerDefinitions",
    "ZendeskListTicketTriggerRevisions",
    "ZendeskCreateTicketTrigger",
    "ZendeskUpdateTicketTrigger",
    "ZendeskDeleteTicketTrigger",
    "ZendeskBulkDeleteTicketTriggers",
    "ZendeskListTargets",
    "ZendeskShowTarget",
    "ZendeskCreateTarget",
    "ZendeskUpdateTarget",
    "ZendeskDeleteTarget",
    "ZendeskListTargetFailures",
    "ZendeskShowTargetFailure",
    "ZendeskListAutomations",
    "ZendeskListActiveAutomations",
    "ZendeskSearchAutomations",
    "ZendeskShowAutomation",
    "ZendeskCreateAutomation",
    "ZendeskUpdateAutomation",
    "ZendeskUpdateManyAutomations",
    "ZendeskDeleteAutomation",
    "ZendeskBulkDeleteAutomations",
    "ZendeskSearchTags",
    "ZendeskListTags",
    "ZendeskCountTags",
    "ZendeskListResourceTags",
    "ZendeskAddTags",
    "ZendeskSetTags",
    "ZendeskRemoveTags",
    "ZendeskListSuspendedTickets",
    "ZendeskShowSuspendedTicket",
    "ZendeskRecoverSuspendedTicket",
    "ZendeskRecoverMultipleSuspendedTickets",
    "ZendeskDeleteSuspendedTicket",
    "ZendeskDeleteMultipleSuspendedTickets",
    "ZendeskSuspendedTicketAttachments",
    "ZendeskExportSuspendedTickets",
    "ZendeskShowOrganizationSubscription",
    "ZendeskListCustomTicketStatuses",
    "ZendeskShowCustomTicketStatus",
    "ZendeskCreateCustomTicketStatus",
    "ZendeskUpdateCustomTicketStatus",
    "ZendeskBulkUpdateDefaultCustomTicketStatuses",
    "ZendeskCreateTicketFormStatusesForCustomStatus",
    "ZendeskListJobStatuses",
    "ZendeskShowJobStatus",
    "ZendeskShowManyJobStatuses",
    "ZendeskListOrganizationSubscriptions",
    "ZendeskCreateOrganizationSubscription",
    "ZendeskDeleteOrganizationSubscription",
    "ZendeskListSessions",
    "ZendeskShowSession",
    "ZendeskShowCurrentSession",
    "ZendeskRenewCurrentSession",
    "ZendeskDeleteSession",
    "ZendeskDeleteCurrentSession",
    "ZendeskListSharingAgreements",
    "ZendeskShowSharingAgreement",
    "ZendeskCreateSharingAgreement",
    "ZendeskUpdateSharingAgreement",
    "ZendeskDeleteSharingAgreement",
    "ZendeskListSlaPolicies",
    "ZendeskShowSlaPolicy",
    "ZendeskCreateSlaPolicy",
    "ZendeskUpdateSlaPolicy",
    "ZendeskDeleteSlaPolicy",
    "ZendeskReorderSlaPolicies",
    "ZendeskRetrieveSlaPolicyFilterDefinitions",
    "ZendeskListGroupSlaPolicies",
    "ZendeskShowGroupSlaPolicy",
    "ZendeskCreateGroupSlaPolicy",
    "ZendeskUpdateGroupSlaPolicy",
    "ZendeskDeleteGroupSlaPolicy",
    "ZendeskListDeletionSchedules",
    "ZendeskCreateDeletionSchedule",
    "ZendeskGetDeletionSchedule",
    "ZendeskUpdateDeletionSchedule",
    "ZendeskDeleteDeletionSchedule",
    "ZendeskListSearchResults",
    "ZendeskShowSearchResultsCount",
    "ZendeskExportSearchResults",
    "ZendeskListCustomRoles",
    "ZendeskShowCustomRole",
    "ZendeskCreateCustomRole",
    "ZendeskUpdateCustomRole",
    "ZendeskDeleteCustomRole",
    "ZendeskListAccountAttributes",
    "ZendeskListRoutingAttributeDefinitions",
    "ZendeskShowRoutingAttribute",
    "ZendeskCreateRoutingAttribute",
    "ZendeskUpdateRoutingAttribute",
    "ZendeskDeleteRoutingAttribute",
    "ZendeskListAttributeValuesForAttribute",
    "ZendeskShowRoutingAttributeValue",
    "ZendeskCreateRoutingAttributeValue",
    "ZendeskUpdateRoutingAttributeValue",
    "ZendeskDeleteRoutingAttributeValue",
    "ZendeskListAgentAttributeValues",
    "ZendeskListAttributeValuesForManyAgents",
    "ZendeskSetAgentAttributeValues",
    "ZendeskSetTicketAttributeValues",
    "ZendeskBulkSetAgentAttributeValuesJob",
    "ZendeskListTicketsFulfilledByUser",
    "ZendeskListTicketAttributeValues",
    "ZendeskCreateTrialAccount",
    "ZendeskVerifySubdomainAvailability",
    "ZendeskListResourceCollections",
    "ZendeskShowResourceCollection",
    "ZendeskCreateResourceCollection",
    "ZendeskUpdateResourceCollection",
    "ZendeskDeleteResourceCollection",
    "ZendeskListRequests",
    "ZendeskSearchRequests",
    "ZendeskShowRequest",
    "ZendeskCreateRequest",
    "ZendeskUpdateRequest",
    "ZendeskListRequestComments",
    "ZendeskShowRequestComment",
    "ZendeskListSatisfactionRatings",
    "ZendeskCountSatisfactionRatings",
    "ZendeskShowSatisfactionRating",
    "ZendeskCreateSatisfactionRating",
    "ZendeskListSatisfactionReasons",
    "ZendeskShowSatisfactionReason",
    "ZendeskChangePassword",
    "ZendeskSetUserPassword",
    "ZendeskListPasswordRequirements",
    "ZendeskListQueues",
    "ZendeskShowQueue",
    "ZendeskCreateQueue",
    "ZendeskUpdateQueue",
    "ZendeskDeleteQueue",
    "ZendeskListQueueDefinitions",
    "ZendeskReorderQueues",
    "ZendeskGetSourcesByTarget",
    "ZendeskListRelationshipFilterDefinitions",
    "ZendeskListCustomObjectRecords",
    "ZendeskShowCustomObjectRecord",
    "ZendeskCreateCustomObjectRecord",
    "ZendeskUpdateCustomObjectRecord",
    "ZendeskDeleteCustomObjectRecord",
    "ZendeskSetCustomObjectRecordByExternalId",
    "ZendeskDeleteCustomObjectRecordByExternalId",
    "ZendeskSearchCustomObjectRecords",
    "ZendeskCountCustomObjectRecords",
    "ZendeskAutocompleteCustomObjectRecords",
    "ZendeskListBrands",
    "ZendeskShowBrand",
    "ZendeskCreateBrand",
    "ZendeskUpdateBrand",
    "ZendeskDeleteBrand",
    "ZendeskCheckHostMappingValidity",
    "ZendeskCheckHostMappingValidityForExistingBrand",
    "ZendeskListOrganizations",
    "ZendeskShowOrganization",
    "ZendeskShowManyOrganizations",
    "ZendeskSearchOrganizations",
    "ZendeskShowOrganizationRelatedInformation",
    "ZendeskCreateOrganization",
    "ZendeskCreateManyOrganizations",
    "ZendeskCreateOrUpdateOrganization",
    "ZendeskUpdateOrganization",
    "ZendeskUpdateManyOrganizations",
    "ZendeskDeleteOrganization",
    "ZendeskBulkDeleteOrganizations",
    "ZendeskCountOrganizations",
    "ZendeskAutocompleteOrganizations",
    "ZendeskMergeOrganizationWithAnotherOrganization",
    "ZendeskShowOrganizationMerge",
    "ZendeskListOrganizationMerges",
    "ZendeskListCustomObjects",
    "ZendeskShowCustomObject",
    "ZendeskCreateCustomObject",
    "ZendeskUpdateCustomObject",
    "ZendeskDeleteCustomObject",
    "ZendeskCustomObjectsLimit",
    "ZendeskListOauthClients",
    "ZendeskListGlobalOauthClients",
    "ZendeskShowOauthClient",
    "ZendeskCreateOauthClient",
    "ZendeskUpdateOauthClient",
    "ZendeskDeleteOauthClient",
    "ZendeskGenerateOauthClientSecret",
    "ZendeskListOauthTokens",
    "ZendeskShowOauthToken",
    "ZendeskCreateOauthToken",
    "ZendeskRevokeOauthToken",
    "ZendeskCreateTokenForGrantType",
    "ZendeskShowTicketMetrics",
    "ZendeskListTicketMetrics",
    "ZendeskListEmailNotifications",
    "ZendeskShowEmailNotification",
    "ZendeskShowManyEmailNotifications",
    "ZendeskListMacros",
    "ZendeskListActiveMacros",
    "ZendeskShowMacro",
    "ZendeskCreateMacro",
    "ZendeskUpdateMacro",
    "ZendeskUpdateManyMacros",
    "ZendeskDeleteMacro",
    "ZendeskBulkDeleteMacros",
    "ZendeskSearchMacros",
    "ZendeskListMacroCategories",
    "ZendeskListMacroActionDefinitions",
    "ZendeskListSupportedActionsForMacros",
    "ZendeskListMacroAttachments",
    "ZendeskShowMacroAttachment",
    "ZendeskShowMacroReplica",
    "ZendeskShowChangesToTicket",
    "ZendeskShowTicketAfterChanges",
    "ZendeskListTicketMetricEvents",
    "ZendeskListGroupMemberships",
    "ZendeskShowGroupMembership",
    "ZendeskCreateGroupMembership",
    "ZendeskDeleteGroupMembership",
    "ZendeskListAssignableMemberships",
    "ZendeskSetGroupMembershipAsDefault",
    "ZendeskListOrganizationMemberships",
    "ZendeskShowOrganizationMembership",
    "ZendeskCreateOrganizationMembership",
    "ZendeskCreateManyMemberships",
    "ZendeskDeleteOrganizationMembership",
    "ZendeskSetOrganizationMembershipAsDefault",
    "ZendeskSetOrganizationAsDefault",
    "ZendeskBulkDeleteGroupMemberships",
    "ZendeskBulkCreateMemberships",
    "ZendeskBulkDeleteOrganizationMemberships",
    "ZendeskUnassignOrganization",
    "ZendeskListIdentities",
    "ZendeskShowIdentity",
    "ZendeskCreateIdentity",
    "ZendeskUpdateIdentity",
    "ZendeskMakeIdentityPrimary",
    "ZendeskRequestUserVerification",
    "ZendeskVerifyIdentity",
    "ZendeskDeleteIdentity",
    "ZendeskTicketImport",
    "ZendeskTicketBulkImport",
    "ZendeskListLocales",
    "ZendeskListLocalesForAgent",
    "ZendeskListAvailablePublicLocales",
    "ZendeskShowCurrentLocale",
    "ZendeskShowLocale",
    "ZendeskDetectBestLanguageForUser",
    "ZendeskIncrementalTicketExportCursor",
    "ZendeskIncrementalTicketExportTimeBased",
    "ZendeskIncrementalTicketEventExport",
    "ZendeskIncrementalUserExportCursor",
    "ZendeskIncrementalUserExportTimeBased",
    "ZendeskIncrementalOrganizationExport",
    "ZendeskIncrementalSampleExport",
    "ZendeskCountTicketFields",
    "ZendeskListTicketFields",
    "ZendeskShowTicketField",
    "ZendeskCreateTicketField",
    "ZendeskUpdateTicketField",
    "ZendeskDeleteTicketField",
    "ZendeskReorderTicketFields",
    "ZendeskListTicketFieldOptions",
    "ZendeskShowTicketFieldOption",
    "ZendeskCreateOrUpdateTicketFieldOption",
    "ZendeskDeleteTicketFieldOption",
    "ZendeskListTicketForms",
    "ZendeskShowTicketForm",
    "ZendeskShowManyTicketForms",
    "ZendeskCreateTicketForm",
    "ZendeskUpdateTicketForm",
    "ZendeskDeleteTicketForm",
    "ZendeskCloneTicketForm",
    "ZendeskReorderTicketForms",
    "ZendeskListTicketFormStatuses",
    "ZendeskCreateTicketFormStatuses",
    "ZendeskBulkUpdateTicketFormStatuses",
    "ZendeskListUserFields",
    "ZendeskShowUserField",
    "ZendeskCreateUserField",
    "ZendeskUpdateUserField",
    "ZendeskDeleteUserField",
    "ZendeskReorderUserField",
    "ZendeskListUserFieldOptions",
    "ZendeskShowUserFieldOption",
    "ZendeskCreateOrUpdateUserFieldOption",
    "ZendeskDeleteUserFieldOption",
    "ZendeskListOrganizationFields",
    "ZendeskShowOrganizationField",
    "ZendeskCreateOrganizationField",
    "ZendeskUpdateOrganizationField",
    "ZendeskDeleteOrganizationField",
    "ZendeskReorderOrganizationField",
    "ZendeskListDynamicContentItems",
    "ZendeskShowDynamicContentItem",
    "ZendeskShowManyDynamicContentItems",
    "ZendeskCreateDynamicContentItem",
    "ZendeskUpdateDynamicContentItem",
    "ZendeskDeleteDynamicContentItem",
    "ZendeskListDynamicContentVariants",
    "ZendeskShowDynamicContentVariant",
    "ZendeskCreateDynamicContentVariant",
    "ZendeskCreateManyDynamicContentVariants",
    "ZendeskUpdateDynamicContentVariant",
    "ZendeskUpdateManyDynamicContentVariants",
    "ZendeskDeleteDynamicContentVariant",
    "ZendeskCreateTicketOrVoicemailTicket",
    "ZendeskOpenUserProfileInAgentWorkspace",
    "ZendeskOpenTicketInAgentBrowser",
    "ZendeskListMonitoredXHandles",
    "ZendeskShowMonitoredXHandle",
    "ZendeskCreateTicketFromTweet",
    "ZendeskListTicketStatuses",
    "ZendeskPushContentToSupport",
    "ZendeskValidateToken",
    "ZendeskReportChannelbackErrorToZendesk",
    "ZendeskReorderGroupSlaPolicies",
    "ZendeskChangeCommentFromPublicToPrivate",
    "ZendeskCountAuditsForTicket",
    "ZendeskExportAuditLogs",
    "ZendeskListAllTicketAudits",
    "ZendeskListAuditLogs",
    "ZendeskListAuditsForTicket",
    "ZendeskShowAudit",
    "ZendeskShowAuditLog",
    "ZendeskSearchArticles",
    "ZendeskDeleteUpload",
    "ZendeskRedactCommentAttachment",
    "ZendeskShowAttachment",
    "ZendeskUpdateAttachmentForMalware",
    "ZendeskUploadFiles",
    "ZendeskCreateApprovalRequest",
    "ZendeskCreateApprovalWorkflowInstance",
    "ZendeskGetApprovalsByApprovalWorkflowId",
    "ZendeskShowApprovalRequest",
    "ZendeskUpdateApprovalRequestStatus",
    "ZendeskListAssignableAgentsFromGroup",
    "ZendeskListAssignableGroupsAndAgentsBasedOnSkill",
    "ZendeskListAssignableGroupsOnAssigneeField",
    "ZendeskListBrandAgentMemberships",
    "ZendeskShowBrandAgentMembership",
    "ZendeskCreateSupportAddress",
    "ZendeskDeleteSupportAddress",
    "ZendeskListSupportAddresses",
    "ZendeskShowSupportAddress",
    "ZendeskUpdateSupportAddress",
    "ZendeskVerifySupportAddressForwarding",
    "ZendeskShowSettings",
    "ZendeskUpdateAccountSettings",
    "ZendeskCountActivities",
    "ZendeskListActivities",
    "ZendeskShowActivity",
    "FalQueueSubmit",
    "FalQueueStatus",
    "FalQueueResult",
    "FalQueueCancel",
    "ElasticsearchIngestAttachment",
    "ElasticsearchBulkOperations",
    "ElasticsearchDeleteDocument",
    "ElasticsearchGetDocument",
    "ElasticsearchIndexDocument",
    "ElasticsearchUpdateDocument",
    "ElasticsearchCreateIndex",
    "ElasticsearchUpdateIndexSettings",
    "ElasticsearchListIndices",
    "ElasticsearchListDocuments",
    "ElasticsearchSearchDocuments",
    "MicrosoftExcelWriteToSheet",
    "MicrosoftExcelClearSheet",
    "MicrosoftExcelCreateSheet",
    "MicrosoftExcelDeleteSheet",
    "MicrosoftExcelListSheets",
    "MicrosoftExcelReadFromSheet",
    "MicrosoftExcelUpdateCell",
    "MicrosoftExcelFindRow",
    "MicrosoftExcelGetCellsInRange",
    "MicrosoftExcelGetRowByIndex",
    "MicrosoftExcelUpdateRow",
    "MicrosoftExcelAddDataToTable",
    "MicrosoftExcelCreateTable",
    "MicrosoftExcelCreateWorkbook",
    "MicrosoftExcelListWorkbooks",
    "MicrosoftExcelGetSheetById",
    "MicrosoftExcelRenameSheet",
    "GeminiImagesEditImage",
    "GeminiImagesGenerateImage",
    "GeminiImagesAnalyzeImage",
    "GeminiImagesGenerateImageWithReference",
    "GeminiImagesImageToBase64",
    "LinkedInSearchPeople",
    "LinkedInSearchCompanies",
    "LinkedInSearchJobs",
    "LinkedInSearch",
    "MongoCreateDocument",
    "MongoFindDocumentById",
    "MongoFindDocument",
    "MongoSearchDocuments",
    "MongoUpdateDocument",
    "MongoUpdateDocuments",
    "MongoDeleteDocument",
    "MongoExecuteAggregation",
    "OneDriveSearchFiles",
    "OneDriveUploadFile",
    "OneDriveListFiles",
    "OneDriveGetFile",
    "OneDriveFindFile",
    "OneDriveDownloadFile",
    "PowerBIListWorkspaces",
    "PowerBIListDatasets",
    "PowerBIGetDataset",
    "PowerBIQueryDataset",
    "PowerBIListReports",
    "PowerBIGetReport",
    "ReplicateCreatePrediction",
    "ReplicateGetPrediction",
    "ReplicateCancelPrediction",
    "ReplicateSearchModels",
    "SalesforceCreateCase",
    "SalesforceUpdateCase",
    "SalesforceDeleteCase",
    "SalesforceCreateComment",
    "SalesforceUpdateComment",
    "SalesforceDeleteComment",
    "SalesforceCreateContact",
    "SalesforceUpdateContact",
    "SalesforceDeleteContact",
    "SalesforceCreateLead",
    "SalesforceGetLead",
    "SalesforceUpdateLead",
    "SalesforceDeleteLead",
    "SalesforceSearchLeads",
    "SalesforceCreateOpportunity",
    "SalesforceUpdateOpportunity",
    "SalesforceDeleteOpportunity",
    "SalesforceCreateTask",
    "SalesforceGetTask",
    "SalesforceUpdateTask",
    "SalesforceDeleteTask",
    "SalesforceSearchTasks",
    "SalesforceQuery",
    "SalesforceCreateRecord",
    "ShopifyGetShopDetails",
    "ShopifyGetProducts",
    "ShopifyGetProduct",
    "ShopifyCreateProduct",
    "ShopifyDeleteProduct",
    "ShopifyGetInventoryLevel",
    "ShopifyAdjustInventory",
    "ShopifyUpdateInventoryTracking",
    "ShopifyGetVariantInventoryItem",
    "DynamicsBCCreateCustomer",
    "DynamicsBCUpdateCustomer",
    "DynamicsBCGetSalesOrder",
    "DynamicsBCGetItemPrices",
    "DynamicsSalesFindContact",
    "DynamicsSalesCreateCustomEntity",
    "DynamicsSalesCreateOpportunity",
    "NetSuiteCreateAccount",
    "NetSuiteDeleteAccount",
    "NetSuiteGetAccount",
    "NetSuiteListAccounts",
    "NetSuiteCreateAssemblyBuild",
    "NetSuiteDeleteAssemblyBuild",
    "NetSuiteGetAssemblyBuild",
    "NetSuiteListAssemblyBuilds",
    "NetSuiteUpdateAssemblyBuild",
    "NetSuiteTransformAssemblyItemToBuild",
    "NetSuiteTransformAssemblyItemToWorkOrder",
    "NetSuiteTransformAssemblyToUnbuild",
    "NetSuiteCreateAssemblyItem",
    "NetSuiteDeleteAssemblyItem",
    "NetSuiteGetAssemblyItem",
    "NetSuiteListAssemblyItems",
    "NetSuiteUpdateAssemblyItem",
    "NetSuiteCreateBillingAccount",
    "NetSuiteDeleteBillingAccount",
    "NetSuiteGetBillingAccount",
    "NetSuiteListBillingAccounts",
    "NetSuiteUpdateBillingAccount",
    "NetSuiteUpsertBillingAccount",
    "NetSuiteCreateBillingSchedule",
    "NetSuiteDeleteBillingSchedule",
    "NetSuiteGetBillingSchedule",
    "NetSuiteListBillingSchedules",
    "NetSuiteUpdateBillingSchedule",
    "NetSuiteUpsertBillingSchedule",
    "NetSuiteCreateCalendarEvent",
    "NetSuiteDeleteCalendarEvent",
    "NetSuiteGetCalendarEvent",
    "NetSuiteListCalendarEvents",
    "NetSuiteUpdateCalendarEvent",
    "NetSuiteUpsertCalendarEvent",
    "NetSuiteCustomSuiteQL",
    "NetSuiteCreateIntercompanyJournalEntry",
    "NetSuiteDeleteIntercompanyJournalEntry",
    "NetSuiteGetIntercompanyJournalEntry",
    "NetSuiteListIntercompanyJournalEntries",
    "NetSuiteUpdateIntercompanyJournalEntry",
    "NetSuiteCreateBinTransfer",
    "NetSuiteDeleteBinTransfer",
    "NetSuiteGetBinTransfer",
    "NetSuiteListBinTransfers",
    "NetSuiteUpdateBinTransfer",
    "NetSuiteUpsertBinTransfer",
    "NetSuiteCreateAccountingPeriod",
    "NetSuiteDeleteAccountingPeriod",
    "NetSuiteSuiteQL",
    "ZohoCrmGetObject",
    "ZohoCrmUpdateObject",
    "ZohoCrmSearchObjects",
    "ZohoCrmListObjects",
    "ZohoCrmListModules",
    "ZohoCrmListFields",
    "ZohoCrmUploadAttachment",
    "ZohoCrmDownloadAttachment",
    "ZohoCrmCreateObject",
    "ZohoCrmConvertLead",
]

_LAZY_IMPORTS = {
    "Bash": ".bash",
    "CalaSearch": ".cala",
    "Edit": ".edit",
    "FirecrawlCrawl": ".firecrawl",
    "FirecrawlExtract": ".firecrawl",
    "FirecrawlMap": ".firecrawl",
    "FirecrawlScrape": ".firecrawl",
    "FirecrawlSearch": ".firecrawl",
    "GmailAddLabel": ".gmail",
    "GmailCreateDraft": ".gmail",
    "GmailListLabels": ".gmail",
    "GmailRemoveLabel": ".gmail",
    "GmailReply": ".gmail",
    "GmailSearch": ".gmail",
    "GmailSend": ".gmail",
    "GoogleCalendarCheckFreeSlots": ".google_calendar",
    "GoogleCalendarCreateEvent": ".google_calendar",
    "GoogleCalendarDeleteEvent": ".google_calendar",
    "GoogleCalendarListEvents": ".google_calendar",
    "GoogleCalendarUpdateAttendeeStatus": ".google_calendar",
    "GoogleCalendarUpdateEvent": ".google_calendar",
    "GoogleDocsCreate": ".google_docs",
    "GoogleDriveCreateFile": ".google_drive",
    "GoogleDriveCreateFolder": ".google_drive",
    "GoogleDriveCreateSharedDrive": ".google_drive",
    "GoogleDriveGetDownloadLink": ".google_drive",
    "GoogleDriveGetFile": ".google_drive",
    "GoogleDriveSearchFiles": ".google_drive",
    "GoogleDriveSearchFolders": ".google_drive",
    "GoogleDriveUploadFile": ".google_drive",
    "GoogleSheetsAddSheet": ".google_sheets",
    "GoogleSheetsAppendValues": ".google_sheets",
    "GoogleSheetsBatchGet": ".google_sheets",
    "GoogleSheetsBatchUpdate": ".google_sheets",
    "GoogleSheetsClearValues": ".google_sheets",
    "GoogleSheetsCopySheet": ".google_sheets",
    "GoogleSheetsCreateSheet": ".google_sheets",
    "GoogleSheetsGetSheetNames": ".google_sheets",
    "GoogleSheetsGetSpreadsheetInfo": ".google_sheets",
    "GoogleSheetsLookupRow": ".google_sheets",
    "GoogleSheetsShareSpreadsheet": ".google_sheets",
    "GoogleMapsNearbySearch": ".google_maps",
    "GoogleMapsPlaceDetails": ".google_maps",
    "GoogleMapsTextSearch": ".google_maps",
    "GoogleMapsValidateAddress": ".google_maps",
    "KnowledgeBaseQuery": ".knowledge_base",
    "OutlookArchive": ".outlook",
    "OutlookCreateDraft": ".outlook",
    "OutlookForward": ".outlook",
    "OutlookGetAttachments": ".outlook",
    "OutlookReadEmails": ".outlook",
    "OutlookSend": ".outlook",
    "OutlookTrash": ".outlook",
    "OutlookUpdateEmail": ".outlook",
    "PineconeCreateIndex": ".pinecone",
    "PineconeDeleteVectors": ".pinecone",
    "PineconeFetchVectors": ".pinecone",
    "PineconeIndexStats": ".pinecone",
    "PineconeListIndexes": ".pinecone",
    "PineconeQuery": ".pinecone",
    "PineconeUpsertVectors": ".pinecone",
    "Read": ".read",
    "ScraperAPIAmazonProduct": ".scraperapi",
    "ScraperAPIAmazonSearch": ".scraperapi",
    "ScraperAPIAsyncScrape": ".scraperapi",
    "ScraperAPIGoogleSearch": ".scraperapi",
    "ScraperAPIScrape": ".scraperapi",
    "TavilyCrawl": ".tavily",
    "TavilyExtract": ".tavily",
    "TavilyMap": ".tavily",
    "TavilySearch": ".tavily",
    "WebSearch": ".web_search",
    "Write": ".write",
    "XSearch": ".xai",
    "ListCharges": ".stripe",
    "CreateCustomer": ".stripe",
    "SearchCustomer": ".stripe",
    "CreatePayment": ".stripe",
    "SendRefund": ".stripe",
    "UpdateCustomer": ".stripe",
    "RetrieveCustomer": ".stripe",
    "ListCustomers": ".stripe",
    "DeleteCustomer": ".stripe",
    "UpdatePaymentIntent": ".stripe",
    "RetrievePaymentIntent": ".stripe",
    "ListPaymentIntents": ".stripe",
    "ConfirmPaymentIntent": ".stripe",
    "CapturePaymentIntent": ".stripe",
    "CancelPaymentIntent": ".stripe",
    "UpdateRefund": ".stripe",
    "RetrieveRefund": ".stripe",
    "ListRefunds": ".stripe",
    "CreateInvoice": ".stripe",
    "UpdateInvoice": ".stripe",
    "RetrieveInvoice": ".stripe",
    "ListInvoices": ".stripe",
    "SendInvoice": ".stripe",
    "FinalizeInvoice": ".stripe",
    "VoidInvoice": ".stripe",
    "WriteOffInvoice": ".stripe",
    "DeleteOrVoidInvoice": ".stripe",
    "CreateInvoiceLineItem": ".stripe",
    "UpdateInvoiceLineItem": ".stripe",
    "RetrieveInvoiceLineItem": ".stripe",
    "DeleteInvoiceLineItem": ".stripe",
    "CreateSubscription": ".stripe",
    "SearchSubscriptions": ".stripe",
    "CancelSubscription": ".stripe",
    "CreateProduct": ".stripe",
    "RetrieveProduct": ".stripe",
    "ListProducts": ".stripe",
    "CreatePrice": ".stripe",
    "RetrievePrice": ".stripe",
    "CreatePayout": ".stripe",
    "UpdatePayout": ".stripe",
    "RetrievePayout": ".stripe",
    "ListPayouts": ".stripe",
    "CancelOrReversePayout": ".stripe",
    "RetrieveBalance": ".stripe",
    "ListBalanceHistory": ".stripe",
    "RetrieveCheckoutSession": ".stripe",
    "RetrieveCheckoutSessionLineItems": ".stripe",
    "CreateBillingMeter": ".stripe",
    "CreateUsageRecord": ".stripe",
    "SlackReadMessages": ".slack",
    "SlackSendMessage": ".slack",
    "SlackSendEphemeralMessage": ".slack",
    "SlackCreateCanvas": ".slack",
    "SlackDeleteMessage": ".slack",
    "SlackGetMessageThread": ".slack",
    "SlackPinMessage": ".slack",
    "SlackUnpinMessage": ".slack",
    "SlackListPinnedItems": ".slack",
    "SlackGetUserPresence": ".slack",
    "SlackSearchUsers": ".slack",
    "SlackAddUserToChannel": ".slack",
    "SlackRemoveFromChannel": ".slack",
    "SlackListUsersInChannel": ".slack",
    "SlackUpdateChannelTopic": ".slack",
    "SlackUpdateChannelPurpose": ".slack",
    "SlackArchiveChannel": ".slack",
    "SlackUnarchiveChannel": ".slack",
    "SlackGetConversationInfo": ".slack",
    "SlackListChannels": ".slack",
    "SlackAddReaction": ".slack",
    "SlackRemoveReaction": ".slack",
    "SlackListFiles": ".slack",
    "SlackGetFileInfo": ".slack",
    "SlackDownloadFile": ".slack",
    "SlackDeleteFile": ".slack",
    "SlackSendAndWaitForResponse": ".slack",
    "LanceDBListTables": ".lancedb",
    "LanceDBCreateTable": ".lancedb",
    "LanceDBDropTable": ".lancedb",
    "LanceDBInsertRecords": ".lancedb",
    "LanceDBVectorSearch": ".lancedb",
    "LanceDBFullTextSearch": ".lancedb",
    "LanceDBHybridSearch": ".lancedb",
    "LanceDBCreateFTSIndex": ".lancedb",
    "LanceDBDropFTSIndex": ".lancedb",
    "LanceDBDeleteRecords": ".lancedb",
    "LanceDBDescribeTable": ".lancedb",
    "HubSpotListContacts": ".hubspot",
    "HubSpotGetContact": ".hubspot",
    "HubSpotCreateContact": ".hubspot",
    "HubSpotUpdateContact": ".hubspot",
    "HubSpotSearchContacts": ".hubspot",
    "HubSpotMergeContacts": ".hubspot",
    "HubSpotGdprDeleteContact": ".hubspot",
    "HubSpotListCompanies": ".hubspot",
    "HubSpotGetCompany": ".hubspot",
    "HubSpotCreateCompany": ".hubspot",
    "HubSpotUpdateCompany": ".hubspot",
    "HubSpotSearchCompanies": ".hubspot",
    "HubSpotListDeals": ".hubspot",
    "HubSpotGetDeal": ".hubspot",
    "HubSpotCreateDeal": ".hubspot",
    "HubSpotUpdateDeal": ".hubspot",
    "HubSpotGetDealPipelines": ".hubspot",
    "HubSpotListTickets": ".hubspot",
    "HubSpotGetTicket": ".hubspot",
    "HubSpotCreateTicket": ".hubspot",
    "HubSpotUpdateTicket": ".hubspot",
    "HubSpotDeleteTicket": ".hubspot",
    "HubSpotMergeTickets": ".hubspot",
    "HubSpotListProducts": ".hubspot",
    "HubSpotGetProduct": ".hubspot",
    "HubSpotCreateProduct": ".hubspot",
    "HubSpotUpdateProduct": ".hubspot",
    "HubSpotDeleteProduct": ".hubspot",
    "HubSpotGetEngagements": ".hubspot",
    "HubSpotGetEngagement": ".hubspot",
    "HubSpotListEngagements": ".hubspot",
    "HubSpotGetRecentEngagements": ".hubspot",
    "HubSpotGetCallDispositions": ".hubspot",
    "HubSpotCreateEngagement": ".hubspot",
    "UpdateEngagement": ".hubspot",
    "HubSpotDeleteEngagement": ".hubspot",
    "HubSpotSendEmail": ".hubspot",
    "HubSpotGetAssociations": ".hubspot",
    "HubSpotCreateAssociation": ".hubspot",
    "HubSpotDeleteAssociation": ".hubspot",
    "HubSpotGetAssociationTypes": ".hubspot",
    "HubSpotGetUsers": ".hubspot",
    "ElevenLabsTextToSpeech": ".elevenlabs",
    "ElevenLabsListPhoneNumbers": ".elevenlabs",
    "ElevenLabsMakeOutboundCall": ".elevenlabs",
    "ElevenLabsListAgents": ".elevenlabs",
    "ElevenLabsGetModels": ".elevenlabs",
    "ElevenLabsGetVoicesWithDescriptions": ".elevenlabs",
    "ElevenLabsListHistory": ".elevenlabs",
    "ElevenLabsGetAudioFromHistoryItem": ".elevenlabs",
    "ElevenLabsDownloadHistoryItems": ".elevenlabs",
    "ElevenLabsCreateAgent": ".elevenlabs",
    "ElevenLabsAddVoice": ".elevenlabs",
    "CloudflareCrawlStart": ".cloudflare",
    "CloudflareCrawlGet": ".cloudflare",
    "CloudflareCrawlCancel": ".cloudflare",
    "AsanaCreateProject": ".asana",
    "AsanaListWorkspaces": ".asana",
    "AsanaUpdateTask": ".asana",
    "AsanaListUserProjects": ".asana",
    "AsanaListTeams": ".asana",
    "AsanaSearchTasks": ".asana",
    "AsanaSearchSections": ".asana",
    "AsanaSearchProjects": ".asana",
    "AsanaListTaskStories": ".asana",
    "AsanaGetTasksFromTaskList": ".asana",
    "AsanaFindTaskById": ".asana",
    "AsanaDeleteTask": ".asana",
    "AsanaCreateTask": ".asana",
    "AsanaCreateTaskFromTemplate": ".asana",
    "AsanaCreateTaskComment": ".asana",
    "AsanaCreateSubtask": ".asana",
    "AsanaAddTaskToSection": ".asana",
    "ZendeskCreateTicket": ".zendesk",
    "ZendeskListTickets": ".zendesk",
    "ZendeskShowTicket": ".zendesk",
    "ZendeskUpdateTicket": ".zendesk",
    "ZendeskSearchTickets": ".zendesk",
    "ZendeskShowManyTickets": ".zendesk",
    "ZendeskUpdateManyTickets": ".zendesk",
    "ZendeskCountTickets": ".zendesk",
    "ZendeskCreateManyTickets": ".zendesk",
    "ZendeskDeleteTicket": ".zendesk",
    "ZendeskBulkDeleteTickets": ".zendesk",
    "ZendeskMarkTicketAsSpam": ".zendesk",
    "ZendeskBulkMarkTicketsAsSpam": ".zendesk",
    "ZendeskMergeTickets": ".zendesk",
    "ZendeskTicketRelatedInformation": ".zendesk",
    "ZendeskListCollaborators": ".zendesk",
    "ZendeskListEmailCcs": ".zendesk",
    "ZendeskListFollowers": ".zendesk",
    "ZendeskListDeletedTickets": ".zendesk",
    "ZendeskRestoreDeletedTicket": ".zendesk",
    "ZendeskRestoreMultipleDeletedTickets": ".zendesk",
    "ZendeskDeleteTicketPermanently": ".zendesk",
    "ZendeskDeleteMultipleTicketsPermanently": ".zendesk",
    "ZendeskListTicketIncidents": ".zendesk",
    "ZendeskListProblems": ".zendesk",
    "ZendeskAutocompleteProblems": ".zendesk",
    "ZendeskCountOrganizationTickets": ".zendesk",
    "ZendeskListUsers": ".zendesk",
    "ZendeskShowUser": ".zendesk",
    "ZendeskListGroups": ".zendesk",
    "ZendeskShowGroup": ".zendesk",
    "ZendeskCountGroups": ".zendesk",
    "ZendeskCreateGroup": ".zendesk",
    "ZendeskUpdateGroup": ".zendesk",
    "ZendeskDeleteGroup": ".zendesk",
    "ZendeskListAssignableGroups": ".zendesk",
    "ZendeskListComments": ".zendesk",
    "ZendeskCountTicketComments": ".zendesk",
    "ZendeskMakeCommentPrivate": ".zendesk",
    "ZendeskRedactTicketCommentInAgentWorkspace": ".zendesk",
    "ZendeskRedactChatComment": ".zendesk",
    "ZendeskRedactChatCommentAttachment": ".zendesk",
    "ZendeskRedactStringInComment": ".zendesk",
    "ZendeskListBookmarks": ".zendesk",
    "ZendeskCreateBookmark": ".zendesk",
    "ZendeskDeleteBookmark": ".zendesk",
    "ZendeskListWorkspaces": ".zendesk",
    "ZendeskShowWorkspace": ".zendesk",
    "ZendeskCreateWorkspace": ".zendesk",
    "ZendeskUpdateWorkspace": ".zendesk",
    "ZendeskDeleteWorkspace": ".zendesk",
    "ZendeskBulkDeleteWorkspaces": ".zendesk",
    "ZendeskReorderWorkspaces": ".zendesk",
    "ZendeskListViews": ".zendesk",
    "ZendeskListViewsCompact": ".zendesk",
    "ZendeskListViewsById": ".zendesk",
    "ZendeskListActiveViews": ".zendesk",
    "ZendeskCountViews": ".zendesk",
    "ZendeskSearchViews": ".zendesk",
    "ZendeskShowView": ".zendesk",
    "ZendeskCreateView": ".zendesk",
    "ZendeskUpdateView": ".zendesk",
    "ZendeskUpdateManyViews": ".zendesk",
    "ZendeskDeleteView": ".zendesk",
    "ZendeskBulkDeleteViews": ".zendesk",
    "ZendeskExecuteView": ".zendesk",
    "ZendeskListTicketsFromView": ".zendesk",
    "ZendeskCountTicketsInView": ".zendesk",
    "ZendeskPreviewViews": ".zendesk",
    "ZendeskPreviewTicketCount": ".zendesk",
    "ZendeskCreateUser": ".zendesk",
    "ZendeskUpdateUser": ".zendesk",
    "ZendeskDeleteUser": ".zendesk",
    "ZendeskSearchUsers": ".zendesk",
    "ZendeskCountUsers": ".zendesk",
    "ZendeskShowManyUsers": ".zendesk",
    "ZendeskShowSelf": ".zendesk",
    "ZendeskShowUserRelatedInformation": ".zendesk",
    "ZendeskListDeletedUsers": ".zendesk",
    "ZendeskShowDeletedUser": ".zendesk",
    "ZendeskCountDeletedUsers": ".zendesk",
    "ZendeskAutocompleteUsers": ".zendesk",
    "ZendeskBulkDeleteUsers": ".zendesk",
    "ZendeskPermanentlyDeleteUser": ".zendesk",
    "ZendeskListTicketTriggerCategories": ".zendesk",
    "ZendeskCreateTicketTriggerCategory": ".zendesk",
    "ZendeskCreateBatchJobForTicketTriggerCategories": ".zendesk",
    "ZendeskShowTicketTriggerCategory": ".zendesk",
    "ZendeskUpdateTicketTriggerCategory": ".zendesk",
    "ZendeskDeleteTicketTriggerCategory": ".zendesk",
    "ZendeskListTicketTriggers": ".zendesk",
    "ZendeskListActiveTicketTriggers": ".zendesk",
    "ZendeskSearchTicketTriggers": ".zendesk",
    "ZendeskShowTicketTrigger": ".zendesk",
    "ZendeskListTicketTriggerDefinitions": ".zendesk",
    "ZendeskListTicketTriggerRevisions": ".zendesk",
    "ZendeskCreateTicketTrigger": ".zendesk",
    "ZendeskUpdateTicketTrigger": ".zendesk",
    "ZendeskDeleteTicketTrigger": ".zendesk",
    "ZendeskBulkDeleteTicketTriggers": ".zendesk",
    "ZendeskListTargets": ".zendesk",
    "ZendeskShowTarget": ".zendesk",
    "ZendeskCreateTarget": ".zendesk",
    "ZendeskUpdateTarget": ".zendesk",
    "ZendeskDeleteTarget": ".zendesk",
    "ZendeskListTargetFailures": ".zendesk",
    "ZendeskShowTargetFailure": ".zendesk",
    "ZendeskListAutomations": ".zendesk",
    "ZendeskListActiveAutomations": ".zendesk",
    "ZendeskSearchAutomations": ".zendesk",
    "ZendeskShowAutomation": ".zendesk",
    "ZendeskCreateAutomation": ".zendesk",
    "ZendeskUpdateAutomation": ".zendesk",
    "ZendeskUpdateManyAutomations": ".zendesk",
    "ZendeskDeleteAutomation": ".zendesk",
    "ZendeskBulkDeleteAutomations": ".zendesk",
    "ZendeskSearchTags": ".zendesk",
    "ZendeskListTags": ".zendesk",
    "ZendeskCountTags": ".zendesk",
    "ZendeskListResourceTags": ".zendesk",
    "ZendeskAddTags": ".zendesk",
    "ZendeskSetTags": ".zendesk",
    "ZendeskRemoveTags": ".zendesk",
    "ZendeskListSuspendedTickets": ".zendesk",
    "ZendeskShowSuspendedTicket": ".zendesk",
    "ZendeskRecoverSuspendedTicket": ".zendesk",
    "ZendeskRecoverMultipleSuspendedTickets": ".zendesk",
    "ZendeskDeleteSuspendedTicket": ".zendesk",
    "ZendeskDeleteMultipleSuspendedTickets": ".zendesk",
    "ZendeskSuspendedTicketAttachments": ".zendesk",
    "ZendeskExportSuspendedTickets": ".zendesk",
    "ZendeskShowOrganizationSubscription": ".zendesk",
    "ZendeskListCustomTicketStatuses": ".zendesk",
    "ZendeskShowCustomTicketStatus": ".zendesk",
    "ZendeskCreateCustomTicketStatus": ".zendesk",
    "ZendeskUpdateCustomTicketStatus": ".zendesk",
    "ZendeskBulkUpdateDefaultCustomTicketStatuses": ".zendesk",
    "ZendeskCreateTicketFormStatusesForCustomStatus": ".zendesk",
    "ZendeskListJobStatuses": ".zendesk",
    "ZendeskShowJobStatus": ".zendesk",
    "ZendeskShowManyJobStatuses": ".zendesk",
    "ZendeskListOrganizationSubscriptions": ".zendesk",
    "ZendeskCreateOrganizationSubscription": ".zendesk",
    "ZendeskDeleteOrganizationSubscription": ".zendesk",
    "ZendeskListSessions": ".zendesk",
    "ZendeskShowSession": ".zendesk",
    "ZendeskShowCurrentSession": ".zendesk",
    "ZendeskRenewCurrentSession": ".zendesk",
    "ZendeskDeleteSession": ".zendesk",
    "ZendeskDeleteCurrentSession": ".zendesk",
    "ZendeskListSharingAgreements": ".zendesk",
    "ZendeskShowSharingAgreement": ".zendesk",
    "ZendeskCreateSharingAgreement": ".zendesk",
    "ZendeskUpdateSharingAgreement": ".zendesk",
    "ZendeskDeleteSharingAgreement": ".zendesk",
    "ZendeskListSlaPolicies": ".zendesk",
    "ZendeskShowSlaPolicy": ".zendesk",
    "ZendeskCreateSlaPolicy": ".zendesk",
    "ZendeskUpdateSlaPolicy": ".zendesk",
    "ZendeskDeleteSlaPolicy": ".zendesk",
    "ZendeskReorderSlaPolicies": ".zendesk",
    "ZendeskRetrieveSlaPolicyFilterDefinitions": ".zendesk",
    "ZendeskListGroupSlaPolicies": ".zendesk",
    "ZendeskShowGroupSlaPolicy": ".zendesk",
    "ZendeskCreateGroupSlaPolicy": ".zendesk",
    "ZendeskUpdateGroupSlaPolicy": ".zendesk",
    "ZendeskDeleteGroupSlaPolicy": ".zendesk",
    "ZendeskListDeletionSchedules": ".zendesk",
    "ZendeskCreateDeletionSchedule": ".zendesk",
    "ZendeskGetDeletionSchedule": ".zendesk",
    "ZendeskUpdateDeletionSchedule": ".zendesk",
    "ZendeskDeleteDeletionSchedule": ".zendesk",
    "ZendeskListSearchResults": ".zendesk",
    "ZendeskShowSearchResultsCount": ".zendesk",
    "ZendeskExportSearchResults": ".zendesk",
    "ZendeskListCustomRoles": ".zendesk",
    "ZendeskShowCustomRole": ".zendesk",
    "ZendeskCreateCustomRole": ".zendesk",
    "ZendeskUpdateCustomRole": ".zendesk",
    "ZendeskDeleteCustomRole": ".zendesk",
    "ZendeskListAccountAttributes": ".zendesk",
    "ZendeskListRoutingAttributeDefinitions": ".zendesk",
    "ZendeskShowRoutingAttribute": ".zendesk",
    "ZendeskCreateRoutingAttribute": ".zendesk",
    "ZendeskUpdateRoutingAttribute": ".zendesk",
    "ZendeskDeleteRoutingAttribute": ".zendesk",
    "ZendeskListAttributeValuesForAttribute": ".zendesk",
    "ZendeskShowRoutingAttributeValue": ".zendesk",
    "ZendeskCreateRoutingAttributeValue": ".zendesk",
    "ZendeskUpdateRoutingAttributeValue": ".zendesk",
    "ZendeskDeleteRoutingAttributeValue": ".zendesk",
    "ZendeskListAgentAttributeValues": ".zendesk",
    "ZendeskListAttributeValuesForManyAgents": ".zendesk",
    "ZendeskSetAgentAttributeValues": ".zendesk",
    "ZendeskSetTicketAttributeValues": ".zendesk",
    "ZendeskBulkSetAgentAttributeValuesJob": ".zendesk",
    "ZendeskListTicketsFulfilledByUser": ".zendesk",
    "ZendeskListTicketAttributeValues": ".zendesk",
    "ZendeskCreateTrialAccount": ".zendesk",
    "ZendeskVerifySubdomainAvailability": ".zendesk",
    "ZendeskListResourceCollections": ".zendesk",
    "ZendeskShowResourceCollection": ".zendesk",
    "ZendeskCreateResourceCollection": ".zendesk",
    "ZendeskUpdateResourceCollection": ".zendesk",
    "ZendeskDeleteResourceCollection": ".zendesk",
    "ZendeskListRequests": ".zendesk",
    "ZendeskSearchRequests": ".zendesk",
    "ZendeskShowRequest": ".zendesk",
    "ZendeskCreateRequest": ".zendesk",
    "ZendeskUpdateRequest": ".zendesk",
    "ZendeskListRequestComments": ".zendesk",
    "ZendeskShowRequestComment": ".zendesk",
    "ZendeskListSatisfactionRatings": ".zendesk",
    "ZendeskCountSatisfactionRatings": ".zendesk",
    "ZendeskShowSatisfactionRating": ".zendesk",
    "ZendeskCreateSatisfactionRating": ".zendesk",
    "ZendeskListSatisfactionReasons": ".zendesk",
    "ZendeskShowSatisfactionReason": ".zendesk",
    "ZendeskChangePassword": ".zendesk",
    "ZendeskSetUserPassword": ".zendesk",
    "ZendeskListPasswordRequirements": ".zendesk",
    "ZendeskListQueues": ".zendesk",
    "ZendeskShowQueue": ".zendesk",
    "ZendeskCreateQueue": ".zendesk",
    "ZendeskUpdateQueue": ".zendesk",
    "ZendeskDeleteQueue": ".zendesk",
    "ZendeskListQueueDefinitions": ".zendesk",
    "ZendeskReorderQueues": ".zendesk",
    "ZendeskGetSourcesByTarget": ".zendesk",
    "ZendeskListRelationshipFilterDefinitions": ".zendesk",
    "ZendeskListCustomObjectRecords": ".zendesk",
    "ZendeskShowCustomObjectRecord": ".zendesk",
    "ZendeskCreateCustomObjectRecord": ".zendesk",
    "ZendeskUpdateCustomObjectRecord": ".zendesk",
    "ZendeskDeleteCustomObjectRecord": ".zendesk",
    "ZendeskSetCustomObjectRecordByExternalId": ".zendesk",
    "ZendeskDeleteCustomObjectRecordByExternalId": ".zendesk",
    "ZendeskSearchCustomObjectRecords": ".zendesk",
    "ZendeskCountCustomObjectRecords": ".zendesk",
    "ZendeskAutocompleteCustomObjectRecords": ".zendesk",
    "ZendeskListBrands": ".zendesk",
    "ZendeskShowBrand": ".zendesk",
    "ZendeskCreateBrand": ".zendesk",
    "ZendeskUpdateBrand": ".zendesk",
    "ZendeskDeleteBrand": ".zendesk",
    "ZendeskCheckHostMappingValidity": ".zendesk",
    "ZendeskCheckHostMappingValidityForExistingBrand": ".zendesk",
    "ZendeskListOrganizations": ".zendesk",
    "ZendeskShowOrganization": ".zendesk",
    "ZendeskShowManyOrganizations": ".zendesk",
    "ZendeskSearchOrganizations": ".zendesk",
    "ZendeskShowOrganizationRelatedInformation": ".zendesk",
    "ZendeskCreateOrganization": ".zendesk",
    "ZendeskCreateManyOrganizations": ".zendesk",
    "ZendeskCreateOrUpdateOrganization": ".zendesk",
    "ZendeskUpdateOrganization": ".zendesk",
    "ZendeskUpdateManyOrganizations": ".zendesk",
    "ZendeskDeleteOrganization": ".zendesk",
    "ZendeskBulkDeleteOrganizations": ".zendesk",
    "ZendeskCountOrganizations": ".zendesk",
    "ZendeskAutocompleteOrganizations": ".zendesk",
    "ZendeskMergeOrganizationWithAnotherOrganization": ".zendesk",
    "ZendeskShowOrganizationMerge": ".zendesk",
    "ZendeskListOrganizationMerges": ".zendesk",
    "ZendeskListCustomObjects": ".zendesk",
    "ZendeskShowCustomObject": ".zendesk",
    "ZendeskCreateCustomObject": ".zendesk",
    "ZendeskUpdateCustomObject": ".zendesk",
    "ZendeskDeleteCustomObject": ".zendesk",
    "ZendeskCustomObjectsLimit": ".zendesk",
    "ZendeskListOauthClients": ".zendesk",
    "ZendeskListGlobalOauthClients": ".zendesk",
    "ZendeskShowOauthClient": ".zendesk",
    "ZendeskCreateOauthClient": ".zendesk",
    "ZendeskUpdateOauthClient": ".zendesk",
    "ZendeskDeleteOauthClient": ".zendesk",
    "ZendeskGenerateOauthClientSecret": ".zendesk",
    "ZendeskListOauthTokens": ".zendesk",
    "ZendeskShowOauthToken": ".zendesk",
    "ZendeskCreateOauthToken": ".zendesk",
    "ZendeskRevokeOauthToken": ".zendesk",
    "ZendeskCreateTokenForGrantType": ".zendesk",
    "ZendeskShowTicketMetrics": ".zendesk",
    "ZendeskListTicketMetrics": ".zendesk",
    "ZendeskListEmailNotifications": ".zendesk",
    "ZendeskShowEmailNotification": ".zendesk",
    "ZendeskShowManyEmailNotifications": ".zendesk",
    "ZendeskListMacros": ".zendesk",
    "ZendeskListActiveMacros": ".zendesk",
    "ZendeskShowMacro": ".zendesk",
    "ZendeskCreateMacro": ".zendesk",
    "ZendeskUpdateMacro": ".zendesk",
    "ZendeskUpdateManyMacros": ".zendesk",
    "ZendeskDeleteMacro": ".zendesk",
    "ZendeskBulkDeleteMacros": ".zendesk",
    "ZendeskSearchMacros": ".zendesk",
    "ZendeskListMacroCategories": ".zendesk",
    "ZendeskListMacroActionDefinitions": ".zendesk",
    "ZendeskListSupportedActionsForMacros": ".zendesk",
    "ZendeskListMacroAttachments": ".zendesk",
    "ZendeskShowMacroAttachment": ".zendesk",
    "ZendeskShowMacroReplica": ".zendesk",
    "ZendeskShowChangesToTicket": ".zendesk",
    "ZendeskShowTicketAfterChanges": ".zendesk",
    "ZendeskListTicketMetricEvents": ".zendesk",
    "ZendeskListGroupMemberships": ".zendesk",
    "ZendeskShowGroupMembership": ".zendesk",
    "ZendeskCreateGroupMembership": ".zendesk",
    "ZendeskDeleteGroupMembership": ".zendesk",
    "ZendeskListAssignableMemberships": ".zendesk",
    "ZendeskSetGroupMembershipAsDefault": ".zendesk",
    "ZendeskListOrganizationMemberships": ".zendesk",
    "ZendeskShowOrganizationMembership": ".zendesk",
    "ZendeskCreateOrganizationMembership": ".zendesk",
    "ZendeskCreateManyMemberships": ".zendesk",
    "ZendeskDeleteOrganizationMembership": ".zendesk",
    "ZendeskSetOrganizationMembershipAsDefault": ".zendesk",
    "ZendeskSetOrganizationAsDefault": ".zendesk",
    "ZendeskBulkDeleteGroupMemberships": ".zendesk",
    "ZendeskBulkCreateMemberships": ".zendesk",
    "ZendeskBulkDeleteOrganizationMemberships": ".zendesk",
    "ZendeskUnassignOrganization": ".zendesk",
    "ZendeskListIdentities": ".zendesk",
    "ZendeskShowIdentity": ".zendesk",
    "ZendeskCreateIdentity": ".zendesk",
    "ZendeskUpdateIdentity": ".zendesk",
    "ZendeskMakeIdentityPrimary": ".zendesk",
    "ZendeskRequestUserVerification": ".zendesk",
    "ZendeskVerifyIdentity": ".zendesk",
    "ZendeskDeleteIdentity": ".zendesk",
    "ZendeskTicketImport": ".zendesk",
    "ZendeskTicketBulkImport": ".zendesk",
    "ZendeskListLocales": ".zendesk",
    "ZendeskListLocalesForAgent": ".zendesk",
    "ZendeskListAvailablePublicLocales": ".zendesk",
    "ZendeskShowCurrentLocale": ".zendesk",
    "ZendeskShowLocale": ".zendesk",
    "ZendeskDetectBestLanguageForUser": ".zendesk",
    "ZendeskIncrementalTicketExportCursor": ".zendesk",
    "ZendeskIncrementalTicketExportTimeBased": ".zendesk",
    "ZendeskIncrementalTicketEventExport": ".zendesk",
    "ZendeskIncrementalUserExportCursor": ".zendesk",
    "ZendeskIncrementalUserExportTimeBased": ".zendesk",
    "ZendeskIncrementalOrganizationExport": ".zendesk",
    "ZendeskIncrementalSampleExport": ".zendesk",
    "ZendeskCountTicketFields": ".zendesk",
    "ZendeskListTicketFields": ".zendesk",
    "ZendeskShowTicketField": ".zendesk",
    "ZendeskCreateTicketField": ".zendesk",
    "ZendeskUpdateTicketField": ".zendesk",
    "ZendeskDeleteTicketField": ".zendesk",
    "ZendeskReorderTicketFields": ".zendesk",
    "ZendeskListTicketFieldOptions": ".zendesk",
    "ZendeskShowTicketFieldOption": ".zendesk",
    "ZendeskCreateOrUpdateTicketFieldOption": ".zendesk",
    "ZendeskDeleteTicketFieldOption": ".zendesk",
    "ZendeskListTicketForms": ".zendesk",
    "ZendeskShowTicketForm": ".zendesk",
    "ZendeskShowManyTicketForms": ".zendesk",
    "ZendeskCreateTicketForm": ".zendesk",
    "ZendeskUpdateTicketForm": ".zendesk",
    "ZendeskDeleteTicketForm": ".zendesk",
    "ZendeskCloneTicketForm": ".zendesk",
    "ZendeskReorderTicketForms": ".zendesk",
    "ZendeskListTicketFormStatuses": ".zendesk",
    "ZendeskCreateTicketFormStatuses": ".zendesk",
    "ZendeskBulkUpdateTicketFormStatuses": ".zendesk",
    "ZendeskListUserFields": ".zendesk",
    "ZendeskShowUserField": ".zendesk",
    "ZendeskCreateUserField": ".zendesk",
    "ZendeskUpdateUserField": ".zendesk",
    "ZendeskDeleteUserField": ".zendesk",
    "ZendeskReorderUserField": ".zendesk",
    "ZendeskListUserFieldOptions": ".zendesk",
    "ZendeskShowUserFieldOption": ".zendesk",
    "ZendeskCreateOrUpdateUserFieldOption": ".zendesk",
    "ZendeskDeleteUserFieldOption": ".zendesk",
    "ZendeskListOrganizationFields": ".zendesk",
    "ZendeskShowOrganizationField": ".zendesk",
    "ZendeskCreateOrganizationField": ".zendesk",
    "ZendeskUpdateOrganizationField": ".zendesk",
    "ZendeskDeleteOrganizationField": ".zendesk",
    "ZendeskReorderOrganizationField": ".zendesk",
    "ZendeskListDynamicContentItems": ".zendesk",
    "ZendeskShowDynamicContentItem": ".zendesk",
    "ZendeskShowManyDynamicContentItems": ".zendesk",
    "ZendeskCreateDynamicContentItem": ".zendesk",
    "ZendeskUpdateDynamicContentItem": ".zendesk",
    "ZendeskDeleteDynamicContentItem": ".zendesk",
    "ZendeskListDynamicContentVariants": ".zendesk",
    "ZendeskShowDynamicContentVariant": ".zendesk",
    "ZendeskCreateDynamicContentVariant": ".zendesk",
    "ZendeskCreateManyDynamicContentVariants": ".zendesk",
    "ZendeskUpdateDynamicContentVariant": ".zendesk",
    "ZendeskUpdateManyDynamicContentVariants": ".zendesk",
    "ZendeskDeleteDynamicContentVariant": ".zendesk",
    "ZendeskCreateTicketOrVoicemailTicket": ".zendesk",
    "ZendeskOpenUserProfileInAgentWorkspace": ".zendesk",
    "ZendeskOpenTicketInAgentBrowser": ".zendesk",
    "ZendeskListMonitoredXHandles": ".zendesk",
    "ZendeskShowMonitoredXHandle": ".zendesk",
    "ZendeskCreateTicketFromTweet": ".zendesk",
    "ZendeskListTicketStatuses": ".zendesk",
    "ZendeskPushContentToSupport": ".zendesk",
    "ZendeskValidateToken": ".zendesk",
    "ZendeskReportChannelbackErrorToZendesk": ".zendesk",
    "ZendeskReorderGroupSlaPolicies": ".zendesk",
    "ZendeskChangeCommentFromPublicToPrivate": ".zendesk",
    "ZendeskCountAuditsForTicket": ".zendesk",
    "ZendeskExportAuditLogs": ".zendesk",
    "ZendeskListAllTicketAudits": ".zendesk",
    "ZendeskListAuditLogs": ".zendesk",
    "ZendeskListAuditsForTicket": ".zendesk",
    "ZendeskShowAudit": ".zendesk",
    "ZendeskShowAuditLog": ".zendesk",
    "ZendeskSearchArticles": ".zendesk",
    "ZendeskDeleteUpload": ".zendesk",
    "ZendeskRedactCommentAttachment": ".zendesk",
    "ZendeskShowAttachment": ".zendesk",
    "ZendeskUpdateAttachmentForMalware": ".zendesk",
    "ZendeskUploadFiles": ".zendesk",
    "ZendeskCreateApprovalRequest": ".zendesk",
    "ZendeskCreateApprovalWorkflowInstance": ".zendesk",
    "ZendeskGetApprovalsByApprovalWorkflowId": ".zendesk",
    "ZendeskShowApprovalRequest": ".zendesk",
    "ZendeskUpdateApprovalRequestStatus": ".zendesk",
    "ZendeskListAssignableAgentsFromGroup": ".zendesk",
    "ZendeskListAssignableGroupsAndAgentsBasedOnSkill": ".zendesk",
    "ZendeskListAssignableGroupsOnAssigneeField": ".zendesk",
    "ZendeskListBrandAgentMemberships": ".zendesk",
    "ZendeskShowBrandAgentMembership": ".zendesk",
    "ZendeskCreateSupportAddress": ".zendesk",
    "ZendeskDeleteSupportAddress": ".zendesk",
    "ZendeskListSupportAddresses": ".zendesk",
    "ZendeskShowSupportAddress": ".zendesk",
    "ZendeskUpdateSupportAddress": ".zendesk",
    "ZendeskVerifySupportAddressForwarding": ".zendesk",
    "ZendeskShowSettings": ".zendesk",
    "ZendeskUpdateAccountSettings": ".zendesk",
    "ZendeskCountActivities": ".zendesk",
    "ZendeskListActivities": ".zendesk",
    "ZendeskShowActivity": ".zendesk",
    "FalQueueSubmit": ".fal",
    "FalQueueStatus": ".fal",
    "FalQueueResult": ".fal",
    "FalQueueCancel": ".fal",
    "ElasticsearchIngestAttachment": ".elasticsearch",
    "ElasticsearchBulkOperations": ".elasticsearch",
    "ElasticsearchDeleteDocument": ".elasticsearch",
    "ElasticsearchGetDocument": ".elasticsearch",
    "ElasticsearchIndexDocument": ".elasticsearch",
    "ElasticsearchUpdateDocument": ".elasticsearch",
    "ElasticsearchCreateIndex": ".elasticsearch",
    "ElasticsearchUpdateIndexSettings": ".elasticsearch",
    "ElasticsearchListIndices": ".elasticsearch",
    "ElasticsearchListDocuments": ".elasticsearch",
    "ElasticsearchSearchDocuments": ".elasticsearch",
    "MicrosoftExcelWriteToSheet": ".excel",
    "MicrosoftExcelClearSheet": ".excel",
    "MicrosoftExcelCreateSheet": ".excel",
    "MicrosoftExcelDeleteSheet": ".excel",
    "MicrosoftExcelListSheets": ".excel",
    "MicrosoftExcelReadFromSheet": ".excel",
    "MicrosoftExcelUpdateCell": ".excel",
    "MicrosoftExcelFindRow": ".excel",
    "MicrosoftExcelGetCellsInRange": ".excel",
    "MicrosoftExcelGetRowByIndex": ".excel",
    "MicrosoftExcelUpdateRow": ".excel",
    "MicrosoftExcelAddDataToTable": ".excel",
    "MicrosoftExcelCreateTable": ".excel",
    "MicrosoftExcelCreateWorkbook": ".excel",
    "MicrosoftExcelListWorkbooks": ".excel",
    "MicrosoftExcelGetSheetById": ".excel",
    "MicrosoftExcelRenameSheet": ".excel",
    "GeminiImagesEditImage": ".gemini_images",
    "GeminiImagesGenerateImage": ".gemini_images",
    "GeminiImagesAnalyzeImage": ".gemini_images",
    "GeminiImagesGenerateImageWithReference": ".gemini_images",
    "GeminiImagesImageToBase64": ".gemini_images",
    "LinkedInSearchPeople": ".linkedin",
    "LinkedInSearchCompanies": ".linkedin",
    "LinkedInSearchJobs": ".linkedin",
    "LinkedInSearch": ".linkedin",
    "MongoCreateDocument": ".mongodb",
    "MongoFindDocumentById": ".mongodb",
    "MongoFindDocument": ".mongodb",
    "MongoSearchDocuments": ".mongodb",
    "MongoUpdateDocument": ".mongodb",
    "MongoUpdateDocuments": ".mongodb",
    "MongoDeleteDocument": ".mongodb",
    "MongoExecuteAggregation": ".mongodb",
    "OneDriveSearchFiles": ".onedrive",
    "OneDriveUploadFile": ".onedrive",
    "OneDriveListFiles": ".onedrive",
    "OneDriveGetFile": ".onedrive",
    "OneDriveFindFile": ".onedrive",
    "OneDriveDownloadFile": ".onedrive",
    "PowerBIListWorkspaces": ".powerbi",
    "PowerBIListDatasets": ".powerbi",
    "PowerBIGetDataset": ".powerbi",
    "PowerBIQueryDataset": ".powerbi",
    "PowerBIListReports": ".powerbi",
    "PowerBIGetReport": ".powerbi",
    "ReplicateCreatePrediction": ".replicate",
    "ReplicateGetPrediction": ".replicate",
    "ReplicateCancelPrediction": ".replicate",
    "ReplicateSearchModels": ".replicate",
    "SalesforceCreateCase": ".salesforce",
    "SalesforceUpdateCase": ".salesforce",
    "SalesforceDeleteCase": ".salesforce",
    "SalesforceCreateComment": ".salesforce",
    "SalesforceUpdateComment": ".salesforce",
    "SalesforceDeleteComment": ".salesforce",
    "SalesforceCreateContact": ".salesforce",
    "SalesforceUpdateContact": ".salesforce",
    "SalesforceDeleteContact": ".salesforce",
    "SalesforceCreateLead": ".salesforce",
    "SalesforceGetLead": ".salesforce",
    "SalesforceUpdateLead": ".salesforce",
    "SalesforceDeleteLead": ".salesforce",
    "SalesforceSearchLeads": ".salesforce",
    "SalesforceCreateOpportunity": ".salesforce",
    "SalesforceUpdateOpportunity": ".salesforce",
    "SalesforceDeleteOpportunity": ".salesforce",
    "SalesforceCreateTask": ".salesforce",
    "SalesforceGetTask": ".salesforce",
    "SalesforceUpdateTask": ".salesforce",
    "SalesforceDeleteTask": ".salesforce",
    "SalesforceSearchTasks": ".salesforce",
    "SalesforceQuery": ".salesforce",
    "SalesforceCreateRecord": ".salesforce",
    "ShopifyGetShopDetails": ".shopify",
    "ShopifyGetProducts": ".shopify",
    "ShopifyGetProduct": ".shopify",
    "ShopifyCreateProduct": ".shopify",
    "ShopifyDeleteProduct": ".shopify",
    "ShopifyGetInventoryLevel": ".shopify",
    "ShopifyAdjustInventory": ".shopify",
    "ShopifyUpdateInventoryTracking": ".shopify",
    "ShopifyGetVariantInventoryItem": ".shopify",
    "DynamicsBCCreateCustomer": ".dynamics_business_central",
    "DynamicsBCUpdateCustomer": ".dynamics_business_central",
    "DynamicsBCGetSalesOrder": ".dynamics_business_central",
    "DynamicsBCGetItemPrices": ".dynamics_business_central",
    "DynamicsSalesFindContact": ".dynamics_sales",
    "DynamicsSalesCreateCustomEntity": ".dynamics_sales",
    "DynamicsSalesCreateOpportunity": ".dynamics_sales",
    "NetSuiteCreateAccount": ".netsuite",
    "NetSuiteDeleteAccount": ".netsuite",
    "NetSuiteGetAccount": ".netsuite",
    "NetSuiteListAccounts": ".netsuite",
    "NetSuiteCreateAssemblyBuild": ".netsuite",
    "NetSuiteDeleteAssemblyBuild": ".netsuite",
    "NetSuiteGetAssemblyBuild": ".netsuite",
    "NetSuiteListAssemblyBuilds": ".netsuite",
    "NetSuiteUpdateAssemblyBuild": ".netsuite",
    "NetSuiteTransformAssemblyItemToBuild": ".netsuite",
    "NetSuiteTransformAssemblyItemToWorkOrder": ".netsuite",
    "NetSuiteTransformAssemblyToUnbuild": ".netsuite",
    "NetSuiteCreateAssemblyItem": ".netsuite",
    "NetSuiteDeleteAssemblyItem": ".netsuite",
    "NetSuiteGetAssemblyItem": ".netsuite",
    "NetSuiteListAssemblyItems": ".netsuite",
    "NetSuiteUpdateAssemblyItem": ".netsuite",
    "NetSuiteCreateBillingAccount": ".netsuite",
    "NetSuiteDeleteBillingAccount": ".netsuite",
    "NetSuiteGetBillingAccount": ".netsuite",
    "NetSuiteListBillingAccounts": ".netsuite",
    "NetSuiteUpdateBillingAccount": ".netsuite",
    "NetSuiteUpsertBillingAccount": ".netsuite",
    "NetSuiteCreateBillingSchedule": ".netsuite",
    "NetSuiteDeleteBillingSchedule": ".netsuite",
    "NetSuiteGetBillingSchedule": ".netsuite",
    "NetSuiteListBillingSchedules": ".netsuite",
    "NetSuiteUpdateBillingSchedule": ".netsuite",
    "NetSuiteUpsertBillingSchedule": ".netsuite",
    "NetSuiteCreateCalendarEvent": ".netsuite",
    "NetSuiteDeleteCalendarEvent": ".netsuite",
    "NetSuiteGetCalendarEvent": ".netsuite",
    "NetSuiteListCalendarEvents": ".netsuite",
    "NetSuiteUpdateCalendarEvent": ".netsuite",
    "NetSuiteUpsertCalendarEvent": ".netsuite",
    "NetSuiteCustomSuiteQL": ".netsuite",
    "NetSuiteCreateIntercompanyJournalEntry": ".netsuite",
    "NetSuiteDeleteIntercompanyJournalEntry": ".netsuite",
    "NetSuiteGetIntercompanyJournalEntry": ".netsuite",
    "NetSuiteListIntercompanyJournalEntries": ".netsuite",
    "NetSuiteUpdateIntercompanyJournalEntry": ".netsuite",
    "NetSuiteCreateBinTransfer": ".netsuite",
    "NetSuiteDeleteBinTransfer": ".netsuite",
    "NetSuiteGetBinTransfer": ".netsuite",
    "NetSuiteListBinTransfers": ".netsuite",
    "NetSuiteUpdateBinTransfer": ".netsuite",
    "NetSuiteUpsertBinTransfer": ".netsuite",
    "NetSuiteCreateAccountingPeriod": ".netsuite",
    "NetSuiteDeleteAccountingPeriod": ".netsuite",
    "NetSuiteSuiteQL": ".netsuite",
    "ZohoCrmGetObject": ".zoho_crm",
    "ZohoCrmUpdateObject": ".zoho_crm",
    "ZohoCrmSearchObjects": ".zoho_crm",
    "ZohoCrmListObjects": ".zoho_crm",
    "ZohoCrmListModules": ".zoho_crm",
    "ZohoCrmListFields": ".zoho_crm",
    "ZohoCrmUploadAttachment": ".zoho_crm",
    "ZohoCrmDownloadAttachment": ".zoho_crm",
    "ZohoCrmCreateObject": ".zoho_crm",
    "ZohoCrmConvertLead": ".zoho_crm",
}


def __getattr__(name: str):
    if name in _LAZY_IMPORTS:
        import importlib

        mod = importlib.import_module(_LAZY_IMPORTS[name], __name__)
        val = getattr(mod, name)
        globals()[name] = val  # cache to bypass __getattr__ on subsequent access
        return val
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
